<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_permisos_funcionarios  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowAdd"]=true;

		$this->events["CustomAdd"]=true;


		$this->events["CustomEdit"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeQueryList"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		/**
 * EVENTO: BeforeDisplay (ADD)
 * MÓDULO: Permisos de Funcionarios (RRHH)
 *
 * OBJETIVO:
 * Ocultar campos que NO deben ser visibles ni editables
 * por el usuario final en el formulario de alta (ADD).
 *
 * MOTIVO:
 * - Estos campos se completan automáticamente desde el sistema
 *   (por lógica interna, auditoría o eventos BeforeAdd / AfterAdd / CustomAdd).
 * - Evita errores de carga manual y mantiene la integridad de los datos.
 *
 * NOTA:
 * - Los campos ocultos se asignan en eventos como BeforeAdd / AfterAdd / CustomAdd.
 * - Si en el futuro se habilita edición administrativa,
 *   esta lógica deberá revisarse.
 */

// Identificador interno del funcionario (se asigna automáticamente)
$pageObject->hideItem("add_id_funcionario");// Oculta el campo id_funcionario

// Estado inicial del permiso (ej: PENDIENTE / CREADO)
$pageObject->hideItem("add_estado");// Oculta el campo estado

// Fecha de creación del registro (auditoría)
$pageObject->hideItem("add_fecha_creacion");// Oculta el campo fecha_creacion

// Usuario que crea el permiso (auditoría)
$pageObject->hideItem("add_usuario_creador");// Oculta el campo usuario_creador

$pageObject->hideItem("add_dependencia_id");// Oculta el campo dependencia_id

$pageObject->hideItem("add_tipo_vinculacion");// Oculta el campo tipo_vinculacion

$pageObject->hideItem("add_email_jefe_id");// Oculta el campo email_jefe_id

// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener Dependencia y datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || '  ' || p.per_apellido AS nombre_completo,
																p.per_cod,
																p.tipo_funcionario_tfun_cod,
																tf.tfun_descri AS descripcion_tipo_funcionario
												FROM personales p
													LEFT JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
													LEFT JOIN tipo_funcionario tf ON tf.tfun_cod = p.tipo_funcionario_tfun_cod
												WHERE p.per_cod = $userPersonal";
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);
$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);
$pageObject->setProxyValue("tipo_funcionario_tfun_cod", $dataDependencia["tipo_funcionario_tfun_cod"]);
$pageObject->setProxyValue("descripcion_tipo_funcionario", $dataDependencia["descripcion_tipo_funcionario"]);

// Query para obtener TODOS los jefes posibles
$sqlEmail = "
	SELECT pe.per_cod,
		pe.per_email_instit,
		car.car_descri
	FROM public.personales pe
		JOIN public.cargos car ON car.car_cod = pe.cargos_car_cod
		JOIN public.personales pe1 ON pe1.dependencias_dep_cod = pe.dependencias_dep_cod
	WHERE car.car_cod IN (4, 5)
	AND pe1.per_cod = {$userPersonal}
";
$resultEmail = CustomQuery($sqlEmail);
$jefes = array();
while ($row = db_fetch_array($resultEmail)) {
	$jefes[] = array(
		"per_cod"    => $row["per_cod"],
		"per_email_instit" => $row["per_email_instit"],
		"car_descri" => $row["car_descri"]
	);
}
// 👉 Pasamos TODO como JSON al frontend(JavaScript Onload event)
$pageObject->setProxyValue("jefes_emails", json_encode($jefes));

;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		/**************************************************************
 * EVENTO: Custom Add
 * DESCRIPCIÓN:
 *  - Inserta un permiso de funcionario en la tabla
 *    rrhh_permisos.permisos_funcionarios
 *  - Obtiene información relacionada (motivo, dependencia)
 *  - Envía un correo electrónico de notificación al jefe
 *    correspondiente.
 **************************************************************/


/*==============================================================
=            INCLUSIÓN DE UTILIDADES / LIBRERÍAS               =
==============================================================*/
// Incluir utilidades de correo electrónico
require_once(getabspath("include/email_utils.php"));



/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
function debug_to_console($data, $context = 'Debug in Console') {
	ob_start();
	$output  = 'console.info(\'' . $context . ':\');';
	$output .= 'console.log(' . json_encode($data) . ');';
	$output  = sprintf('<script>%s</script>', $output);
	echo $output;
}


/*==============================================================
=            DATOS DEL USUARIO LOGUEADO                        =
==============================================================*/
// Obtener información del usuario actualmente autenticado
$currentUserData = Security::currentUserData();


/*==============================================================
=            OBTENCIÓN DE VALORES DEL FORMULARIO               =
==============================================================*/
/**
 * $values contiene los campos enviados desde el formulario ADD
 * Estos valores luego serán insertados en la base de datos
 */
$dependencia_id = $values["dependencia_id"];
$id_funcionario = $values["id_funcionario"]; // per_cod
$fecha_desde = $values["fecha_desde"];
$hora_desde = $values["hora_desde"];
$motivo_id = $values["motivo_id"];
$comision_servicios = $values["comision_servicios"];
$comision_servicios_descripcion = $values["comision_servicios_descripcion"];
$observacion = $values["observacion"];
$tipo_vinculacion = $values["tipo_vinculacion"];
$nombre_completo = $values["nombre_completo"];
$fecha_hasta = $values["fecha_hasta"];
$hora_hasta = $values["hora_hasta"];
$estado = "PENDIENTE"; // Estado inicial
$archivo_adjunto = $values["archivo_adjunto"];
$email_jefe = $values["email_jefe"];
$email_jefe_id = $values["email_jefe_id"];
$nombreDependencia = $values["descripcion_dependencia"];

/*==============================================================
=            OBTENER DESCRIPCIÓN DEL MOTIVO                    =
==============================================================*/
$sqlMotivo = DB::PrepareSQL(
"SELECT tip_descripcion 
FROM public.tipos_ocurrencias 
WHERE tip_cod = ':1'", $values["motivo_id"]
);
//debug_to_console($sqlMotivo);
$resultMotivo = DB::Query($sqlMotivo);
$rowMotivo = $resultMotivo->fetchAssoc();
$nombreMotivo = $rowMotivo ? $rowMotivo['tip_descripcion'] : 'No especificado';

/*==============================================================
=            INSERCIÓN DEL PERMISO Y ENVÍO DE CORREO           =
==============================================================*/
try {
	/*--------------------------------------------
	| Insertar permiso en la base de datos
	--------------------------------------------*/
	$sqlInsertPermisosFuncionarios = DB::PrepareSQL(
		"INSERT INTO rrhh_permisos.permisos_funcionarios (id_funcionario,
																													tipo_vinculacion,
																													dependencia_id,
																													fecha_desde,
																													hora_desde,
																													fecha_hasta,
																													hora_hasta,
																													motivo_id,
																													comision_servicios,
																													comision_servicios_descripcion,
																													observacion,
																													estado,
																													archivo_adjunto,
																													solicitado_por,
																													fecha_solicitud,
																													resultado_decision,
																													rrhh_resultado_decision) 
			VALUES (':1',':2',':3',':4',':5',':6',':7',':8',':9',':10',':11',':12',':13',':14',NOW(),':15',':16')
				RETURNING id",
				$id_funcionario,
				$tipo_vinculacion,
				$dependencia_id,
				$fecha_desde,
				$hora_desde,
				$fecha_hasta,
				$hora_hasta,
				$motivo_id,
				$comision_servicios,
				$comision_servicios_descripcion,
				$observacion,
				$estado,
				$archivo_adjunto,
				$currentUserData["usu_cod"],
				$estado,
				$estado
	);
	//debug_to_console($sqlInsertPermisosFuncionarios);

	$resultPermisosFuncionarios = DB::Query($sqlInsertPermisosFuncionarios);
	$row_permisos_funcionarios = $resultPermisosFuncionarios->fetchAssoc();
	$permiso_funcionario_id = $row_permisos_funcionarios['id'];
	
	// ============================================================================
	// ENVÍO DE CORREO ELECTRÓNICO DE NOTIFICACIÓN
	// ============================================================================
	/*-----------------------------------------------------
	| Preparar datos del permiso para el correo electrónico
	------------------------------------------------------*/
	$datosPermiso = array(
					'nombre_funcionario' => trim($nombre_completo),
					'fecha_desde' => $fecha_desde,
					'hora_desde' => $hora_desde,
					'fecha_hasta' => $fecha_hasta,
					'hora_hasta' => $hora_hasta,
					'motivo' => $nombreMotivo,
					'observacion' => $observacion,
					'dependencia' => $nombreDependencia,
					'email_jefe_id' => $email_jefe_id
	);

	/*--------------------------------------------
	| Enviar correo de notificación
	--------------------------------------------*/
	$emailEnviado = EmailUtils::enviarNotificacionSolicitudPermiso(
		$datosPermiso, 
		$permiso_funcionario_id,
		$email_jefe
	);

	if ($emailEnviado) {
		error_log("Correo enviado para permiso ID: " . $permiso_funcionario_id);
		debug_to_console("Correo enviado para permiso ID: " . $permiso_funcionario_id);
	} else {
		error_log("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
		debug_to_console("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
	}

} catch (Exception $e) {
	// Si ocurre un error en el correo, NO se revierte la inserción del permiso.
	error_log("Excepción al enviar correo: " . $e->getMessage());
	debug_to_console("Excepción al enviar correo: " . $e->getMessage());
}

;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		/******************************************************************************************
 * EVENTO: Custom record update (Edit Page)
 * MÓDULO: Permisos de Funcionarios (RRHH)
 *
 * DESCRIPCIÓN GENERAL:
 * Este evento se ejecuta cuando el usuario edita un registro de permisos
 * y presiona el botón "Guardar".
 *
 * Se utiliza este evento para:
 *  - Tomar control total del proceso de actualización
 *  - Ejecutar manualmente el UPDATE sobre la tabla permisos_funcionarios
 *  - Evitar que PHPRunner ejecute su actualización automática
 *
 * NOTA:
 *  - El array $values contiene los valores actuales del formulario Edit
 *  - El método DB::PrepareSQL() previene inyecciones SQL
 *  - El `return false` cancela el update automático de PHPRunner
 ******************************************************************************************/

/*==============================================================
=            INCLUSIÓN DE UTILIDADES / LIBRERÍAS               =
==============================================================*/
// Incluir utilidades de correo electrónico
require_once(getabspath("include/email_utils.php"));


/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
function debug_to_console($data, $context = 'Debug in Console') {
	ob_start();
	$output  = 'console.info(\'' . $context . ':\');';
	$output .= 'console.log(' . json_encode($data) . ');';
	$output  = sprintf('<script>%s</script>', $output);
	echo $output;
}

/**
 * $values contiene los campos enviados desde el formulario ADD
 * Estos valores luego serán insertados en la base de datos
 */
$fecha_desde = $values["fecha_desde"];
$hora_desde = $values["hora_desde"];
$observacion = $values["observacion"];
$nombre_completo = $values["nombre_completo_edit"];
$fecha_hasta = $values["fecha_hasta"];
$hora_hasta = $values["hora_hasta"];
$email_jefe = $values["email_jefe"];
$email_jefe_id = $values["email_jefe_id"];
$nombreDependencia = $values["descripcion_dependencia_edit"];

/*==============================================================
=            OBTENER DESCRIPCIÓN DEL MOTIVO                    =
==============================================================*/
$sqlMotivo = DB::PrepareSQL(
	"SELECT tip_descripcion 
	FROM public.tipos_ocurrencias 
	WHERE tip_cod = ':1'", $values["motivo_id"]
);
//debug_to_console($sqlMotivo);
$resultMotivo = DB::Query($sqlMotivo);
$rowMotivo = $resultMotivo->fetchAssoc();
$nombreMotivo = $rowMotivo ? $rowMotivo['tip_descripcion'] : 'No especificado';


//if (!$fecha_desde || !$fecha_hasta) {
//	$message = "Debe completar las fechas desde y hasta.";
//	return false;
//}
//if (strtotime($fecha_hasta) < strtotime($fecha_desde)) {
//	$message = "La fecha hasta no puede ser menor que la fecha desde.";
//	return false;
//}

/*==============================================================
=        ACTUALIZACIÓN DEL PERMISO Y ENVÍO DE CORREO           =
==============================================================*/
try {
	/*--------------------------------------------
	| Actualizar permiso en la base de datos
	--------------------------------------------*/

	// Construcción del SQL de actualización del permiso del funcionario
	$update_permiso_func = DB::PrepareSQL("UPDATE rrhh_permisos.permisos_funcionarios 
																									SET tipo_vinculacion = ':1',
																										dependencia_id = ':2',
																										fecha_desde = ':3',
																										hora_desde = ':4',
																										fecha_hasta = ':5',
																										hora_hasta = ':6',
																										motivo_id = ':7',
																										comision_servicios = ':8',
																										comision_servicios_descripcion = ':9',
																										observacion = ':10',
																										fecha_actualizacion = ':11',
																										archivo_adjunto = ':12'
																									WHERE id = ':13'",
																										$values["tipo_vinculacion"],
																										$values["dependencia_id"],
																										$values["fecha_desde"],
																										$values["hora_desde"],
																										$values["fecha_hasta"],
																										$values["hora_hasta"],
																										$values["motivo_id"],
																										$values["comision_servicios"],
																										$values["comision_servicios_descripcion"],
																										$values["observacion"],
																										now(),
																										$values["archivo_adjunto"],
																										$values["id"]);
	// Ejecución del UPDATE en la base de datos
	DB::Exec($update_permiso_func);
	//debug_to_console("update_permiso_func: " . $update_permiso_func);
	$permiso_funcionario_id = $values["id"];
	
	// ============================================================================
	// ENVÍO DE CORREO ELECTRÓNICO DE NOTIFICACIÓN
	// ============================================================================
	/*-----------------------------------------------------
	| Preparar datos del permiso para el correo electrónico
	------------------------------------------------------*/
	$datosPermiso = array(
					'nombre_funcionario' => trim($nombre_completo),
					'fecha_desde' => $fecha_desde,
					'hora_desde' => $hora_desde,
					'fecha_hasta' => $fecha_hasta,
					'hora_hasta' => $hora_hasta,
					'motivo' => $nombreMotivo,
					'observacion' => $observacion,
					'dependencia' => $nombreDependencia,
					'email_jefe_id' => $email_jefe_id
	);


	/*--------------------------------------------
	| Enviar correo de notificación
	--------------------------------------------*/
	$emailEnviado = EmailUtils::enviarNotificacionSolicitudPermiso(
		$datosPermiso, 
		$permiso_funcionario_id,
		$email_jefe
	);

	if ($emailEnviado) {
		error_log("Correo enviado para permiso ID: " . $permiso_funcionario_id);
		debug_to_console("Correo enviado para permiso ID: " . $permiso_funcionario_id);
	} else {
		error_log("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
		debug_to_console("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
	}

} catch (Exception $e) {
	// Si ocurre un error en el correo, NO se revierte la inserción del permiso.
	error_log("Excepción al enviar correo: " . $e->getMessage());
	debug_to_console("Excepción al enviar correo: " . $e->getMessage());
}



;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->hideItem("edit_id"); // Oculta el campo id
$pageObject->hideItem("edit_dependencia_id");
$pageObject->hideItem("edit_email_jefe_id"); // Oculta el campo email_jefe_id
$pageObject->hideItem("edit_tipo_vinculacion"); // Oculta el campo tipo_vinculacion

// Se creo un campo falso 'nombre_completo_edit', porque no puedo hacer el envio desde el formulario
// del campo real porque es un campo de solo lectura y al ser solo readOnly no se puede enviar, solucion provisoria.
$pageObject->hideItem("nombre_completo_edit");
$pageObject->hideItem("descripcion_dependencia_edit");

// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener Dependencia y datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || ' ' || p.per_apellido AS nombre_completo,
																p.per_cod,
																p.tipo_funcionario_tfun_cod,
																tf.tfun_descri AS descripcion_tipo_funcionario
												FROM personales p
													LEFT JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
													LEFT JOIN tipo_funcionario tf ON tf.tfun_cod = p.tipo_funcionario_tfun_cod
												WHERE p.per_cod = $userPersonal";
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);
$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);
$pageObject->setProxyValue("tipo_funcionario_tfun_cod", $dataDependencia["tipo_funcionario_tfun_cod"]);
$pageObject->setProxyValue("descripcion_tipo_funcionario", $dataDependencia["descripcion_tipo_funcionario"]);

// Query para obtener TODOS los jefes posibles
$sqlEmail = "
	SELECT pe.per_cod,
		pe.per_email_instit,
		car.car_descri
	FROM public.personales pe
		JOIN public.cargos car ON car.car_cod = pe.cargos_car_cod
		JOIN public.personales pe1 ON pe1.dependencias_dep_cod = pe.dependencias_dep_cod
	WHERE car.car_cod IN (4, 5)
	AND pe1.per_cod = {$userPersonal}
";
$resultEmail = CustomQuery($sqlEmail);
$jefes = array();
while ($row = db_fetch_array($resultEmail)) {
	$jefes[] = array(
		"per_cod"    => $row["per_cod"],
		"per_email_instit" => $row["per_email_instit"],
		"car_descri" => $row["car_descri"]
	);
}

// 👉 Pasamos TODO como JSON al frontend(JavaScript Onload event)
$pageObject->setProxyValue("jefes_emails", json_encode($jefes));

;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$currentUser = Security::currentUserData();
$userPersonal = (int)$currentUser["usu_personal"];

// Solo pendientes del usuario
/*$strWhereClause .= "
    AND pf.estado = 'PENDIENTE'
    AND pf.id_funcionario = {$userPersonal}
";*/

$strWhereClause .= "
    AND pf.id_funcionario = {$userPersonal}
";
;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		// $pageObject->setMessageType(MESSAGE_SUCCESS);
$pageObject->setMessageType(1);

$html_exitoso = '
<div style="
    border: 1px solid #28a745;
    background-color: #e9f7ef;
    color: #155724;
    padding: 18px 22px;
    border-radius: 6px;
    margin: 15px 0;
">
    <h4 style="margin-top:0; color:#1e7e34;">
        ✅ ¡Solicitud enviada con éxito!
    </h4>

    <p style="margin: 8px 0; color:#155724; font-size: 18px;">
       Tu solicitud de permiso fue registrada correctamente y enviada a tu superior inmediato para su revisión.
    </p>
		<a href="permisos_funcionarios_list.php" style="
        display: inline-block;
        margin-top: 12px;
        padding: 8px 14px;
        background-color: #28a745;
        color: #ffffff;
        text-decoration: none;
        border-radius: 4px;
        font-weight: 500;
    ">
        ⬅ Volver al Listado
    </a>
</div>
';

$pageObject->setMessage($html_exitoso);

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		
$pageObject->hideItem("grid_edit", $recordId); // Oculta inicialmente el boton de edicion.

if ($data["resultado_decision"] == 'PENDIENTE') {
	$pageObject->showItem("grid_edit", $recordId); // Muestra el boton de edicion.
} else {
	$pageObject->hideItem("grid_edit", $recordId); // Oculta el boton de edicion.
}


;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$pageObject->setMessageType(1);

$html_exitoso = '
<div style="
    border: 1px solid #28a745;
    background-color: #e9f7ef;
    color: #155724;
    padding: 18px 22px;
    border-radius: 6px;
    margin: 15px 0;
">
    <h4 style="margin-top:0; color:#1e7e34;">
        ✅ ¡Solicitud enviada con éxito!
    </h4>

    <p style="margin: 8px 0; color:#155724; font-size: 18px;">
       Tu solicitud de permiso fue actualizada correctamente y enviada a tu superior inmediato para su revisión.
    </p>

    <a href="permisos_funcionarios_list.php" style="
        display: inline-block;
        margin-top: 12px;
        padding: 8px 14px;
        background-color: #28a745;
        color: #ffffff;
        text-decoration: none;
        border-radius: 4px;
        font-weight: 500;
    ">
        ⬅ Volver al Listado
    </a>
</div>
';

$pageObject->setMessage($html_exitoso);

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		// EVENTO: Before record added

$camposRequeridos = [
	"dependencia_id"   => "Dependencia",
	"tipo_vinculacion" => "Tipo de vinculación"
];

$faltantes = [];

foreach ($camposRequeridos as $campo => $label) {
	if (!isset($values[$campo]) || trim($values[$campo]) === "") {
		$faltantes[] = $label;
	}
}

if (!empty($faltantes)) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Faltan completar los siguientes datos de tu perfil:</b>
		<ul style='margin-top:8px'>
			<li>" . implode("</li><li>", $faltantes) . "</li>
		</ul>
		Por favor, comunícate con el área de <b>Recursos Humanos</b> para actualizar tu información.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}


if (!$values["fecha_desde"] || !$values["fecha_hasta"]) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Faltan completar los siguientes datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Fecha Desde / Fecha Hasta</li>
		</ul>
		Por favor, envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}

if (strtotime($values["fecha_hasta"]) < strtotime($values["fecha_desde"])) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Inconsistencia en los datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Fecha Desde / Fecha Hasta</li>
		</ul>
		La <b>fecha desde</b> no puede ser menor que la <b>fecha hasta</b>
		<br>
		Por favor corrige y envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}


if (!$values["email_jefe_id"]) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Faltan completar los siguientes datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Correo electrónico del superior inmediato</li>
		</ul>
		Por favor, envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}


return true;

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

//return true;


if (!$values["fecha_desde"] || !$values["fecha_hasta"]) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Faltan completar los siguientes datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Fecha Desde / Fecha Hasta</li>
		</ul>
		Por favor, envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}

if (strtotime($values["fecha_hasta"]) < strtotime($values["fecha_desde"])) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Inconsistencia en los datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Fecha Desde / Fecha Hasta</li>
		</ul>
		La <b>fecha desde</b> no puede ser menor que la <b>fecha hasta</b>
		<br>
		Por favor corrige y envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}


if (!$values["email_jefe_id"]) {
	$mensaje = "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ No es posible enviar la solicitud de permiso.</b>
		<br>
		<br>
		<b>Faltan completar los siguientes datos del formulario:</b>
		<ul style='margin-top:8px'>
			<li>Correo electrónico del superior inmediato</li>
		</ul>
		Por favor, envia toda la información necesaria.
	</div>";
	$message = $mensaje;
	
	return false; // ⛔ DETIENE TODO
}


return true;

;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
