<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_permisos_funcionarios  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowAdd"]=true;

		$this->events["CustomAdd"]=true;


		$this->events["CustomEdit"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeQueryList"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;


		$this->events["BeforeShowView"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		/**
 * EVENTO: BeforeDisplay (ADD)
 * MÓDULO: Permisos de Funcionarios (RRHH)
 *
 * OBJETIVO:
 * Ocultar campos que NO deben ser visibles ni editables
 * por el usuario final en el formulario de alta (ADD).
 *
 * MOTIVO:
 * - Estos campos se completan automáticamente desde el sistema
 *   (por lógica interna, auditoría o eventos BeforeAdd / AfterAdd / CustomAdd).
 * - Evita errores de carga manual y mantiene la integridad de los datos.
 *
 * NOTA:
 * - Los campos ocultos se asignan en eventos como BeforeAdd / AfterAdd / CustomAdd.
 * - Si en el futuro se habilita edición administrativa,
 *   esta lógica deberá revisarse.
 */


/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
//function debug_to_console($data, $context = 'Debug in Console') {
//	ob_start();
//	$output  = 'console.info(\'' . $context . ':\');';
//	$output .= 'console.log(' . json_encode($data) . ');';
//	$output  = sprintf('<script>%s</script>', $output);
//	echo $output;
//}

// Identificador interno del funcionario (se asigna automáticamente)
$pageObject->hideItem("add_id_funcionario");// Oculta el campo id_funcionario

// Estado inicial del permiso (ej: PENDIENTE / CREADO)
$pageObject->hideItem("add_estado");// Oculta el campo estado

// Fecha de creación del registro (auditoría)
$pageObject->hideItem("add_fecha_creacion");// Oculta el campo fecha_creacion

// Usuario que crea el permiso (auditoría)
$pageObject->hideItem("add_usuario_creador");// Oculta el campo usuario_creador

$pageObject->hideItem("add_dependencia_id");// Oculta el campo dependencia_id

$pageObject->hideItem("add_tipo_vinculacion");// Oculta el campo tipo_vinculacion

$pageObject->hideItem("add_email_jefe_id");// Oculta el campo email_jefe_id

$pageObject->hideItem("add_save"); // Oculta el boton Guardar que trae por defecto.

$pageObject->hideItem("text_email_jefe"); // Oculta el texto de email_jefe.

$pageObject->hideItem("add_sex_descripcion"); // Oculta el campo sex_descripcion








// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || '  ' || p.per_apellido AS nombre_completo,
																p.per_cod,
																p.tipo_funcionario_tfun_cod,
																tf.tfun_descri AS descripcion_tipo_funcionario,
																TO_CHAR(AGE(CURRENT_DATE, p.per_ingreso), 'YY \"años, \" MM \"meses y \" DD \"días\"') AS antiguedad_laboral,
																c.car_descri,
																s.sed_descripcion,
																s2.sex_descripcion
												FROM personales p
													LEFT JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
													LEFT JOIN tipo_funcionario tf ON tf.tfun_cod = p.tipo_funcionario_tfun_cod
													LEFT JOIN cargos c ON c.car_cod = p.cargos_car_cod
													LEFT JOIN sedes s ON s.sed_cod = p.per_sede
													LEFT JOIN sexos s2 ON p.per_sexo::integer = s2.sex_cod
												WHERE p.per_cod = $userPersonal";
//debug_to_console("sqlDependencia: " . $sqlDependencia);
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);
$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);
$pageObject->setProxyValue("tipo_funcionario_tfun_cod", $dataDependencia["tipo_funcionario_tfun_cod"]);
$pageObject->setProxyValue("descripcion_tipo_funcionario", $dataDependencia["descripcion_tipo_funcionario"]);
$pageObject->setProxyValue("antiguedad_laboral", $dataDependencia["antiguedad_laboral"]);
$pageObject->setProxyValue("car_descri", $dataDependencia["car_descri"]);
$pageObject->setProxyValue("sed_descripcion", $dataDependencia["sed_descripcion"]);
$pageObject->setProxyValue("sex_descripcion", $dataDependencia["sex_descripcion"]);



// Query para obtener TODOS los jefes posibles del usuario logueado.
$sqlEmail = "
	SELECT public.vw_personales_superiores.superior_cod AS per_cod, 
					public.vw_personales_superiores.superior_email AS per_email_instit, 
					public.vw_personales_superiores.cargo_superior AS car_descri
	FROM public.vw_personales_superiores
	WHERE public.vw_personales_superiores.funcionario_cod = {$userPersonal}
";
//debug_to_console("sqlEmail: " . $sqlEmail);
//print_r($_SESSION);
$resultEmail = CustomQuery($sqlEmail);
$jefes = array();
while ($row = db_fetch_array($resultEmail)) {
	$jefes[] = array(
		"per_cod"    => $row["per_cod"],
		"per_email_instit" => $row["per_email_instit"],
		"car_descri" => $row["car_descri"]
	);
}
// 👉 Pasamos TODO como JSON al frontend(JavaScript Onload event)
$pageObject->setProxyValue("jefes_emails", json_encode($jefes));


// Query para obtener el conteo de cantidad de permisos por mes.
$sqlTotalPermisos = DB::PrepareSQL(
"SELECT TO_CHAR(fecha_solicitud, 'TMMonth') AS mes_nombre, 
				COUNT(*) AS cantidad_permisos_mes
FROM rrhh_permisos.permisos_funcionarios
WHERE id_funcionario = ':1'
  AND EXTRACT(MONTH FROM fecha_solicitud) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND EXTRACT(YEAR FROM fecha_solicitud) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY TO_CHAR(fecha_solicitud, 'TMMonth')", $userPersonal
);
//debug_to_console("sqlTotalPermisos: " . $sqlTotalPermisos);
$resultTotalPermisos = DB::Query($sqlTotalPermisos);
$rowTotalPermisos = $resultTotalPermisos->fetchAssoc();
if ($rowTotalPermisos && $rowTotalPermisos['cantidad_permisos_mes'] > 0) {
	$cantidad_permisos_mes = $rowTotalPermisos['cantidad_permisos_mes'];
} else {
	$cantidad_permisos_mes = 0;
}
//debug_to_console("mes_nombre: " . $rowTotalPermisos['mes_nombre'] . ", total_permisos: " . $rowTotalPermisos['cantidad_permisos_mes']);
$pageObject->setProxyValue("cantidad_permisos_mes", $cantidad_permisos_mes);


;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		/**************************************************************
 * EVENTO: Custom Add
 * DESCRIPCIÓN:
 *  - Inserta un permiso de funcionario en la tabla
 *    rrhh_permisos.permisos_funcionarios
 *  - Obtiene información relacionada (motivo, dependencia)
 *  - Envía un correo electrónico de notificación al jefe
 *    correspondiente.
 **************************************************************/


/*==============================================================
=            INCLUSIÓN DE UTILIDADES / LIBRERÍAS               =
==============================================================*/
// Incluir utilidades de correo electrónico
require_once(getabspath("include/email_utils.php"));



/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
//function debug_to_console($data, $context = 'Debug in Console') {
//	ob_start();
//	$output  = 'console.info(\'' . $context . ':\');';
//	$output .= 'console.log(' . json_encode($data) . ');';
//	$output  = sprintf('<script>%s</script>', $output);
//	echo $output;
//}


/*==============================================================
=            DATOS DEL USUARIO LOGUEADO                        =
==============================================================*/
// Obtener información del usuario actualmente autenticado
$currentUserData = Security::currentUserData();


/*==============================================================
=            OBTENCIÓN DE VALORES DEL FORMULARIO               =
==============================================================*/
/**
 * $values contiene los campos enviados desde el formulario ADD
 * Estos valores luego serán insertados en la base de datos
 */
$dependencia_id = $values["dependencia_id"];
$id_funcionario = $values["id_funcionario"]; // per_cod
$fecha_desde = $values["fecha_desde"];
$hora_desde = $values["hora_desde"];
$motivo_id = $values["motivo_id"];
//$comision_servicios = $values["comision_servicios"];
//$comision_servicios_descripcion = $values["comision_servicios_descripcion"];
$observacion = $values["observacion"];
$tipo_vinculacion = $values["tipo_vinculacion"];
$nombre_completo = $values["nombre_completo"];
$fecha_hasta = $values["fecha_hasta"];
$hora_hasta = $values["hora_hasta"];
$estado = "PENDIENTE"; // Estado inicial
$archivo_adjunto = $values["archivo_adjunto"];
$email_jefe = $values["email_jefe"];
$email_jefe_id = $values["email_jefe_id"];
$nombreDependencia = $values["descripcion_dependencia"];

/*==============================================================
=            OBTENER DESCRIPCIÓN DEL MOTIVO                    =
==============================================================*/
$sqlMotivo = DB::PrepareSQL(
"SELECT tip_descripcion 
FROM public.tipos_ocurrencias 
WHERE tip_cod = ':1'", $values["motivo_id"]
);
//debug_to_console($sqlMotivo);
$resultMotivo = DB::Query($sqlMotivo);
$rowMotivo = $resultMotivo->fetchAssoc();
$nombreMotivo = $rowMotivo ? $rowMotivo['tip_descripcion'] : 'No especificado';

/*==============================================================
=            INSERCIÓN DEL PERMISO Y ENVÍO DE CORREO           =
==============================================================*/
try {
	/*--------------------------------------------
	| Insertar permiso en la base de datos
	--------------------------------------------*/
	$sqlInsertPermisosFuncionarios = DB::PrepareSQL(
		"INSERT INTO rrhh_permisos.permisos_funcionarios (id_funcionario,
																														tipo_vinculacion,
																														dependencia_id,
																														fecha_desde,
																														hora_desde,
																														fecha_hasta,
																														hora_hasta,
																														motivo_id,
																														observacion,
																														estado,
																														archivo_adjunto,
																														solicitado_por,
																														fecha_solicitud,
																														resultado_decision,
																														rrhh_resultado_decision) 
		VALUES (':1',':2',':3',':4',':5',':6',':7',':8',':9',':10',':11',':12',NOW(),':13',':14')
				RETURNING id",
				$id_funcionario,
				$tipo_vinculacion,
				$dependencia_id,
				$fecha_desde,
				$hora_desde,
				$fecha_hasta,
				$hora_hasta,
				$motivo_id,
				$observacion,
				$estado,
				$archivo_adjunto,
				$currentUserData["usu_cod"],
				$estado,
				$estado
	);
	//debug_to_console($sqlInsertPermisosFuncionarios);
	
	$resultPermisosFuncionarios = DB::Query($sqlInsertPermisosFuncionarios);
	$row_permisos_funcionarios = $resultPermisosFuncionarios->fetchAssoc();
	$permiso_funcionario_id = $row_permisos_funcionarios['id'];
	//debug_to_console("Permiso generado con ID: ".$permiso_funcionario_id);
	
	// ============================================================================
	// ENVÍO DE CORREO ELECTRÓNICO DE NOTIFICACIÓN
	// ============================================================================
	/*-----------------------------------------------------
	| Preparar datos del permiso para el correo electrónico
	------------------------------------------------------*/
	$datosPermiso = array(
					'nombre_funcionario' => trim($nombre_completo),
					'fecha_desde' => $fecha_desde,
					'hora_desde' => $hora_desde,
					'fecha_hasta' => $fecha_hasta,
					'hora_hasta' => $hora_hasta,
					'motivo' => $nombreMotivo,
					'observacion' => $observacion,
					'dependencia' => $nombreDependencia,
					'email_jefe_id' => $email_jefe_id,
					'tipo_solicitud' => 'permiso'
	);

	/*--------------------------------------------
	| Enviar correo de notificación							|
	--------------------------------------------*/
	$emailEnviado = EmailUtils::enviarNotificacionSolicitudPermiso(
		$datosPermiso, 
		$permiso_funcionario_id,
		$email_jefe
	);

	if ($emailEnviado) {
		error_log("Correo enviado para permiso ID: " . $permiso_funcionario_id);
		//debug_to_console("Correo enviado para permiso ID: " . $permiso_funcionario_id);
	} else {
		error_log("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
		//debug_to_console("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
	}

} catch (Exception $e) {
	// Si ocurre un error en el correo, NO se revierte la inserción del permiso.
	error_log("Excepción al enviar correo: " . $e->getMessage());
	//debug_to_console("Excepción al enviar correo: " . $e->getMessage());
}

;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		/******************************************************************************************
 * EVENTO: Custom record update (Edit Page)
 * MÓDULO: Permisos de Funcionarios (RRHH)
 *
 * DESCRIPCIÓN GENERAL:
 * Este evento se ejecuta cuando el usuario edita un registro de permisos
 * y presiona el botón "Guardar".
 *
 * Se utiliza este evento para:
 *  - Tomar control total del proceso de actualización
 *  - Ejecutar manualmente el UPDATE sobre la tabla permisos_funcionarios
 *  - Evitar que PHPRunner ejecute su actualización automática
 *
 * NOTA:
 *  - El array $values contiene los valores actuales del formulario Edit
 *  - El método DB::PrepareSQL() previene inyecciones SQL
 *  - El `return false` cancela el update automático de PHPRunner
 ******************************************************************************************/

/*==============================================================
=            INCLUSIÓN DE UTILIDADES / LIBRERÍAS               =
==============================================================*/
// Incluir utilidades de correo electrónico
require_once(getabspath("include/email_utils.php"));


/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
//function debug_to_console($data, $context = 'Debug in Console') {
//	ob_start();
//	$output  = 'console.info(\'' . $context . ':\');';
//	$output .= 'console.log(' . json_encode($data) . ');';
//	$output  = sprintf('<script>%s</script>', $output);
//	echo $output;
//}

/**
 * $values contiene los campos enviados desde el formulario ADD
 * Estos valores luego serán insertados en la base de datos
 */
$fecha_desde = $values["fecha_desde"];
$hora_desde = $values["hora_desde"];
$observacion = $values["observacion"];
$nombre_completo = $values["nombre_completo_edit"];
$fecha_hasta = $values["fecha_hasta"];
$hora_hasta = $values["hora_hasta"];
$email_jefe = $values["email_jefe"];
$email_jefe_id = $values["email_jefe_id"];
$nombreDependencia = $values["descripcion_dependencia_edit"];

if (!isset($values["intentos_correccion"])) {
	$values["intentos_correccion"] = $oldvalues["intentos_correccion"];
}


/*==============================================================
=            OBTENER DESCRIPCIÓN DEL MOTIVO                    =
==============================================================*/
$sqlMotivo = DB::PrepareSQL(
	"SELECT tip_descripcion 
	FROM public.tipos_ocurrencias 
	WHERE tip_cod = ':1'", $values["motivo_id"]
);
//debug_to_console($sqlMotivo);
$resultMotivo = DB::Query($sqlMotivo);
$rowMotivo = $resultMotivo->fetchAssoc();
$nombreMotivo = $rowMotivo ? $rowMotivo['tip_descripcion'] : 'No especificado';


/*==============================================================
=        ACTUALIZACIÓN DEL PERMISO Y ENVÍO DE CORREO           =
==============================================================*/
try {
	/*--------------------------------------------
	| Actualizar permiso en la base de datos
	--------------------------------------------*/

	// Construcción del SQL de actualización del permiso del funcionario
	/*$update_permiso_func = DB::PrepareSQL("UPDATE rrhh_permisos.permisos_funcionarios 
																									SET tipo_vinculacion = ':1',
																										dependencia_id = ':2',
																										fecha_desde = ':3',
																										hora_desde = ':4',
																										fecha_hasta = ':5',
																										hora_hasta = ':6',
																										motivo_id = ':7',
																										comision_servicios = ':8',
																										comision_servicios_descripcion = ':9',
																										observacion = ':10',
																										fecha_actualizacion = ':11',
																										archivo_adjunto = ':12',
																										intentos_correccion = ':13',
																										rrhh_resultado_decision = ':14',
																										rrhh_motivo_rechazo = ':15'
																									WHERE id = ':16'",
																										$values["tipo_vinculacion"],
																										$values["dependencia_id"],
																										$values["fecha_desde"],
																										$values["hora_desde"],
																										$values["fecha_hasta"],
																										$values["hora_hasta"],
																										$values["motivo_id"],
																										$values["comision_servicios"],
																										$values["comision_servicios_descripcion"],
																										$values["observacion"],
																										now(),
																										$values["archivo_adjunto"],
																										$values["intentos_correccion"],
																										$values["rrhh_resultado_decision"],
																										$values["rrhh_motivo_rechazo"],
																										$values["id"]);*/
	$update_permiso_func = DB::PrepareSQL("UPDATE rrhh_permisos.permisos_funcionarios 
																									SET tipo_vinculacion = ':1',
																										dependencia_id = ':2',
																										fecha_desde = ':3',
																										hora_desde = ':4',
																										fecha_hasta = ':5',
																										hora_hasta = ':6',
																										motivo_id = ':7',
																										observacion = ':8',
																										fecha_actualizacion = ':9',
																										archivo_adjunto = ':10',
																										intentos_correccion = ':11',
																										rrhh_resultado_decision = ':12',
																										rrhh_motivo_rechazo = ':13'
																									WHERE id = ':14'",
																										$values["tipo_vinculacion"],
																										$values["dependencia_id"],
																										$values["fecha_desde"],
																										$values["hora_desde"],
																										$values["fecha_hasta"],
																										$values["hora_hasta"],
																										$values["motivo_id"],
																										$values["observacion"],
																										now(),
																										$values["archivo_adjunto"],
																										$values["intentos_correccion"],
																										$values["rrhh_resultado_decision"],
																										$values["rrhh_motivo_rechazo"],
																										$values["id"]);
	// Ejecución del UPDATE en la base de datos
	DB::Exec($update_permiso_func);
	//debug_to_console("update_permiso_func: " . $update_permiso_func);
	$permiso_funcionario_id = $values["id"];

	
	if ($enviar_mail_jefe == 1) {
		// ============================================================================
		// ENVÍO DE CORREO ELECTRÓNICO DE NOTIFICACIÓN
		// ============================================================================
		/*-----------------------------------------------------
		| Preparar datos del permiso para el correo electrónico
		------------------------------------------------------*/
		$datosPermiso = array(
						'nombre_funcionario' => trim($nombre_completo),
						'fecha_desde' => $fecha_desde,
						'hora_desde' => $hora_desde,
						'fecha_hasta' => $fecha_hasta,
						'hora_hasta' => $hora_hasta,
						'motivo' => $nombreMotivo,
						'observacion' => $observacion,
						'dependencia' => $nombreDependencia,
						'email_jefe_id' => $email_jefe_id,
						'tipo_solicitud' => 'permiso',
		);


		/*--------------------------------------------
		| Enviar correo de notificación
		| - Toda la logica y programacion del envio de correo
		| se encuentra en el archivo: output\include\email_utils.php
		--------------------------------------------*/
		$emailEnviado = EmailUtils::enviarNotificacionSolicitudPermiso(
			$datosPermiso, 
			$permiso_funcionario_id,
			$email_jefe
		);

		if ($emailEnviado) {
			error_log("Correo enviado para permiso ID: " . $permiso_funcionario_id);
			//debug_to_console("Correo enviado para permiso ID: " . $permiso_funcionario_id);
		} else {
			error_log("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
			//debug_to_console("Error al enviar correo para permiso ID: " . $permiso_funcionario_id);
		}
	} // FIN '$enviar_mail_jefe == 1'
	
} catch (Exception $e) {
	// Si ocurre un error en el correo, NO se revierte la inserción del permiso.
	error_log("Excepción al enviar correo: " . $e->getMessage());
	//debug_to_console("Excepción al enviar correo: " . $e->getMessage());
}



;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
//function debug_to_console($data, $context = 'Debug in Console') {
//	ob_start();
//	$output  = 'console.info(\'' . $context . ':\');';
//	$output .= 'console.log(' . json_encode($data) . ');';
//	$output  = sprintf('<script>%s</script>', $output);
//	echo $output;
//}

$pageObject->hideItem("edit_id"); // Oculta el campo id
$pageObject->hideItem("edit_dependencia_id");
$pageObject->hideItem("edit_email_jefe_id"); // Oculta el campo email_jefe_id
$pageObject->hideItem("edit_tipo_vinculacion"); // Oculta el campo tipo_vinculacion
$pageObject->hideItem("edit_save"); // Oculta el boton Guardar que trae por defecto.

// Se creo un campo falso 'nombre_completo_edit', porque no puedo hacer el envio desde el formulario
// del campo real porque es un campo de solo lectura y al ser solo readOnly no se puede enviar, es una solucion provisoria...
$pageObject->hideItem("nombre_completo_edit");
$pageObject->hideItem("descripcion_dependencia_edit");

$pageObject->hideItem("text_email_jefe_edit"); // Oculta el texto email_jefe_edit

$pageObject->hideItem("edit_decidido_por"); // Oculta el campo decidido_por

$pageObject->hideItem("edit_id_funcionario"); // Oculta el campo id_funcionario

$pageObject->hideItem("edit_sex_descripcion"); // Oculta el campo sex_descripcion


$pageObject->hideItem("text6");
$pageObject->hideItem("edit_comision_servicios");
$pageObject->hideItem("edit_comision_servicios_descripcion");
$pageObject->hideItem("text7");



// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener Dependencia y datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || ' ' || p.per_apellido AS nombre_completo,
																p.per_cod,
																p.tipo_funcionario_tfun_cod,
																tf.tfun_descri AS descripcion_tipo_funcionario,
																TO_CHAR(AGE(CURRENT_DATE, p.per_ingreso), 'YY \"años, \" MM \"meses y \" DD \"días\"') AS antiguedad_laboral,
																c.car_descri,
																s.sed_descripcion,
																s2.sex_descripcion
												FROM personales p
													LEFT JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
													LEFT JOIN tipo_funcionario tf ON tf.tfun_cod = p.tipo_funcionario_tfun_cod
													LEFT JOIN cargos c ON c.car_cod = p.cargos_car_cod
													LEFT JOIN sedes s ON s.sed_cod = p.per_sede
													LEFT JOIN sexos s2 ON p.per_sexo::integer = s2.sex_cod
												WHERE p.per_cod = $userPersonal";
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);

$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);
$pageObject->setProxyValue("tipo_funcionario_tfun_cod", $dataDependencia["tipo_funcionario_tfun_cod"]);
$pageObject->setProxyValue("descripcion_tipo_funcionario", $dataDependencia["descripcion_tipo_funcionario"]);
$pageObject->setProxyValue("antiguedad_laboral", $dataDependencia["antiguedad_laboral"]);
$pageObject->setProxyValue("car_descri", $dataDependencia["car_descri"]);
$pageObject->setProxyValue("sed_descripcion", $dataDependencia["sed_descripcion"]);
$pageObject->setProxyValue("sex_descripcion", $dataDependencia["sex_descripcion"]);

// Query para obtener TODOS los jefes posibles
//$sqlEmail = "
//	SELECT pe.per_cod,
//		pe.per_email_instit,
//		car.car_descri
//	FROM public.personales pe
//		JOIN public.cargos car ON car.car_cod = pe.cargos_car_cod
//		JOIN public.personales pe1 ON pe1.dependencias_dep_cod = pe.dependencias_dep_cod
//	WHERE car.car_cod IN (4, 5)
//	AND pe1.per_cod = {$userPersonal}
//";
$sqlEmail = "
	SELECT public.vw_personales_superiores.superior_cod AS per_cod, 
					public.vw_personales_superiores.superior_email AS per_email_instit, 
					public.vw_personales_superiores.cargo_superior AS car_descri
	FROM public.vw_personales_superiores
	WHERE public.vw_personales_superiores.funcionario_cod = {$userPersonal}
";
$resultEmail = CustomQuery($sqlEmail);
$jefes = array();
while ($row = db_fetch_array($resultEmail)) {
	$jefes[] = array(
		"per_cod"    => $row["per_cod"],
		"per_email_instit" => $row["per_email_instit"],
		"car_descri" => $row["car_descri"]
	);
}

// 👉 Pasamos TODO como JSON al frontend(JavaScript Onload event)
$pageObject->setProxyValue("jefes_emails", json_encode($jefes));



// Query para obtener el conteo de cantidad de permisos por mes.
$sqlTotalPermisos = DB::PrepareSQL(
"SELECT TO_CHAR(fecha_solicitud, 'TMMonth') AS mes_nombre, 
				COUNT(*) AS cantidad_permisos_mes
FROM rrhh_permisos.permisos_funcionarios
WHERE id_funcionario = ':1'
  AND EXTRACT(MONTH FROM fecha_solicitud) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND EXTRACT(YEAR FROM fecha_solicitud) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY TO_CHAR(fecha_solicitud, 'TMMonth')", $userPersonal
);
//debug_to_console("sqlTotalPermisos: " . $sqlTotalPermisos);
$resultTotalPermisos = DB::Query($sqlTotalPermisos);
$rowTotalPermisos = $resultTotalPermisos->fetchAssoc();
if ($rowTotalPermisos && $rowTotalPermisos['cantidad_permisos_mes'] > 0) {
	$cantidad_permisos_mes = $rowTotalPermisos['cantidad_permisos_mes'];
} else {
	$cantidad_permisos_mes = 0;
}
//debug_to_console("mes_nombre: " . $rowTotalPermisos['mes_nombre'] . ", total_permisos: " . $rowTotalPermisos['cantidad_permisos_mes']);
$pageObject->setProxyValue("cantidad_permisos_mes", $cantidad_permisos_mes);

;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		$currentUser = Security::currentUserData();
$userPersonal = (int)$currentUser["usu_personal"];

// Solo pendientes del usuario
/*$strWhereClause .= "
    AND pf.estado = 'PENDIENTE'
    AND pf.id_funcionario = {$userPersonal}
";*/

// Todos los estados del usuario
$strWhereClause .= "
    AND pf.id_funcionario = {$userPersonal}
";


;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		// $pageObject->setMessageType(MESSAGE_SUCCESS);
$pageObject->setMessageType(1);

$html_exitoso = '
<div style="
    border: 1px solid #28a745;
    background-color: #e9f7ef;
    color: #155724;
    padding: 18px 22px;
    border-radius: 6px;
    margin: 15px 0;
">
    <h4 style="margin-top:0; color:#1e7e34;">
        ✅ ¡Solicitud enviada con éxito!
    </h4>

    <p style="margin: 8px 0; color:#155724; font-size: 18px;">
       Tu solicitud de permiso fue registrada correctamente y enviada a tu superior inmediato para su revisión.
    </p>
		<a href="permisos_funcionarios_list.php" style="
        display: inline-block;
        margin-top: 12px;
        padding: 8px 14px;
        background-color: #28a745;
        color: #ffffff;
        text-decoration: none;
        border-radius: 4px;
        font-weight: 500;
    ">
        ⬅ Volver al Listado
    </a>
</div>
';

$pageObject->setMessage($html_exitoso);

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		/*
$pageObject->hideItem("grid_edit", $recordId); // Oculta inicialmente el boton de edicion.

if ($data["resultado_decision"] == 'PENDIENTE') {
	$pageObject->showItem("grid_edit", $recordId); // Muestra el boton de edicion.
} else {
	$pageObject->hideItem("grid_edit", $recordId); // Oculta el boton de edicion.
}
*/


$pageObject->hideItem("grid_edit", $recordId); // Oculta inicialmente el boton de edicion.
$pageObject->hideItem("list_intentos_correccion"); // Oculta el campo intentos de correcion(necesario para el 'edit')

if ($data["resultado_decision"] == 'PENDIENTE'
			OR ($data["rrhh_resultado_decision"] == 'RECHAZADO' AND $data["intentos_correccion"] < 1) ) {
	$pageObject->showItem("grid_edit", $recordId); // Muestra el boton de edicion.
} else {
	$pageObject->hideItem("grid_edit", $recordId); // Oculta el boton de edicion.
}

;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$pageObject->setMessageType(1);

$html_exitoso = '
<div style="
    border: 1px solid #28a745;
    background-color: #e9f7ef;
    color: #155724;
    padding: 18px 22px;
    border-radius: 6px;
    margin: 15px 0;
">
    <h4 style="margin-top:0; color:#1e7e34;">
        ✅ ¡Solicitud enviada con éxito!
    </h4>

    <p style="margin: 8px 0; color:#155724; font-size: 18px;">
       Tu solicitud de permiso fue actualizada correctamente y enviada a tu superior inmediato para su revisión.
    </p>

    <a href="permisos_funcionarios_list.php" style="
        display: inline-block;
        margin-top: 12px;
        padding: 8px 14px;
        background-color: #28a745;
        color: #ffffff;
        text-decoration: none;
        border-radius: 4px;
        font-weight: 500;
    ">
        ⬅ Volver al Listado
    </a>
</div>
';

$pageObject->setMessage($html_exitoso);

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
function debug_to_console($data, $context = 'Debug in Console') {
	ob_start();
	$output  = 'console.info(\'' . $context . ':\');';
	$output .= 'console.log(' . json_encode($data) . ');';
	$output  = sprintf('<script>%s</script>', $output);
	echo $output;
	
	//ob_start();
	//$json_data = json_encode($data, JSON_UNESCAPED_UNICODE);
	//$script =  "console.group('PHP " . addslashes($context) . "');";
	//$script .= "console.log(" . $json_data . ");";
	//$script .= "console.groupEnd();";
	//printf('<script>%s</script>', $script);
}


/**
 * ============================================================
 * 🎨 GENERADOR DE MENSAJES DE ERROR VISUALES
 * ============================================================
 * Genera un bloque HTML estilizado para mostrar errores al usuario.
 *
 * @param string $titulo
 * @param string $descripcion
 * @param array  $items Lista opcional de detalles
 * @param string $footer Texto adicional (ej: instrucciones)
 */
function generarMensajeError($titulo, $descripcion, $items = [], $footer = "") {
	$htmlItems = "";
	
	if (!empty($items)) {
		$htmlItems .= "<ul style='margin-top:8px'>";
		foreach ($items as $item) {
			$htmlItems .= "<li>$item</li>";
		}
		$htmlItems .= "</ul>";
	}
	
	return "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ $titulo</b>
		<br><br>
		<b>$descripcion</b>
		$htmlItems
		$footer
	</div>";
}


/**
 * ============================================================
 * 👤 VALIDACIÓN DE DATOS DEL PERFIL DEL FUNCIONARIO
 * ============================================================
 * Se valida que el funcionario tenga datos básicos completos.
 * Estos datos NO se cargan en el formulario directamente,
 * pero son necesarios para procesar correctamente el permiso.
 * Verifica que el usuario tenga completos los datos básicos
 * antes de permitir enviar una solicitud.
 */
$camposRequeridosPerfil = [
	"descripcion_dependencia" => "Dependencia",
	"descripcion_tipo_vinculacion" => "Tipo de vinculación"
];

$faltantesPerfil = [];

foreach ($camposRequeridosPerfil as $campo => $label) {
	if (!isset($values[$campo]) || trim($values[$campo]) === "") {
		$faltantesPerfil[] = $label;
	}
}

// ⛔ Si faltan datos → detener proceso
if (!empty($faltantesPerfil)) {
	$message = generarMensajeError(
		"No es posible enviar la solicitud de permiso.",
		"Faltan completar los siguientes datos de tu perfil:",
		$faltantesPerfil,
		"Por favor, comunícate con la <b>Dirección General de Talentos Humanos</b> para actualizar tu información."
	);
	
	return false; // ⛔ DETIENE TODO
}
// FIN VALIDACIÓN DE PERFIL DEL FUNCIONARIO


/**
 * ============================================================
 * 📝 VALIDACIÓN DE CAMPOS DEL FORMULARIO
 * ============================================================
 * Verifica que todos los campos obligatorios estén completos.
 */
$camposRequeridosFormulario = [
	"motivo_id" => "Tipo de permiso o justificación",
	"fecha_desde" => "Fecha desde",
	"hora_desde" => "Hora de inicio",
	"fecha_hasta" => "Fecha hasta",
	"hora_hasta" => "Hora de fin",
	"email_jefe_id" => "Correo electrónico del superior inmediato"
];

$faltantesFormulario = [];

foreach ($camposRequeridosFormulario as $campoForm => $labelForm) {
	if (!isset($values[$campoForm]) || trim($values[$campoForm]) === "") {
		$faltantesFormulario[] = $labelForm;
	}
}

// ⛔ Si faltan datos → detener proceso
if (!empty($faltantesFormulario)) {
	$message = generarMensajeError(
		"No es posible enviar la solicitud de permiso.",
		"Falta completar los siguientes datos del formulario:",
		$faltantesFormulario,
		"Por favor, completa los campos obligatorios del formulario."
	);

	return false; // ⛔ DETIENE TODO
}
// FIN VALIDACIÓN DE CAMPOS DEL FORMULARIO


$motivo_id = $values["motivo_id"];
//debug_to_console("motivo_id: " . $motivo_id);

// Obtener la descripcion del tipo de permiso para un mensaje más claro para el usuario.
$sqlMotivoDesc = "SELECT * 
										FROM public.tipos_ocurrencias 
										WHERE tip_cod = $motivo_id";
$rsMotivoDesc = DB::Query($sqlMotivoDesc);
$dataMotivoDesc = $rsMotivoDesc->fetchAssoc();
$tip_descripcion = $dataMotivoDesc["tip_descripcion"];
$tip_dias = $dataMotivoDesc["tip_dias"];
$tip_cantidad_maxima_mes = $dataMotivoDesc["tip_cantidad_maxima_mes"];
$tip_cantidad_maxima_anho = $dataMotivoDesc["tip_cantidad_maxima_anho"];
$tip_presentacion_cantidad = $dataMotivoDesc["tip_presentacion_cantidad"];
$tip_genero_permitido = $dataMotivoDesc["tip_genero_permitido"];
//debug_to_console("tip_descripcion: " . $tip_descripcion . ", tip_dias: " . $tip_dias . ", tip_cantidad_maxima_mes: " . $tip_cantidad_maxima_mes . ", tip_cantidad_maxima_anho: " . $tip_cantidad_maxima_anho);


/**
 * ============================================================
 * 📅 FUNCIONES AUXILIARES DE FECHAS
 * ============================================================
 */

/**
 * Funcion que calcula dias entre fechas.
 * Genera un array con todas las fechas entre inicio y fin
 */
function lista_dias($inicio, $fin) {
	$rango = array();
	if (is_string($inicio) === true) $inicio = strtotime($inicio);
	if (is_string($fin) === true ) $fin = strtotime($fin);
	if ($inicio > $fin) return createDateRangeArray($fin, $inicio);
	
	do {
		$rango[] = date('Y-m-d', $inicio);
		$inicio = strtotime("+ 1 day", $inicio);
	} while($inicio <= $fin);
	
	return $rango;
}

/**
 * Obtiene lista de feriados desde BD
 */
function lista_feriados() {
	$lista_feriados = array();
	$sql_feriados = "select fer_fecha from feriados";
	$resultado_feriados = CustomQuery($sql_feriados);
	while($feriado = db_fetch_array($resultado_feriados)) {
		array_push($lista_feriados, $feriado['fer_fecha']);
	}
	return $lista_feriados;
}

/**
 * ============================================================
 * 📊 CÁLCULO DE DÍAS UTILIZADOS
 * ============================================================
 * Calcula días consumidos considerando:
 * - Fines de semana
 * - Feriados
 * - Tipo de días (corridos o hábiles)
 */
function gasto_dias($lista_dias, $tipo_dias) {
	$resultado = array();
	$meses_gasto = array();
	$cantida_total_meses = 0;
	$mes = 0;
	$anho = 0;
	$dias = 0;
	$cantidad_dias = 0;
	$corridos = $tipo_dias;
	$feriados = lista_feriados();
	
	foreach ($lista_dias as $valor) {
		if (((date('w', strtotime($valor)) != 6) and (date('w', strtotime($valor)) != 0) and array_search($valor, $feriados, true) === FALSE ) OR $corridos == 1) {	
			$dias = $dias + 1;
			$cantidad_dias = $dias;
			if ($anho == 0 or $anho <> date("Y", strtotime($valor))) {
				$anho = date("Y", strtotime($valor));
				$mes = number_format(date("m", strtotime($valor)));
				$cantida_total_meses = $cantida_total_meses + 1;
				$dias = 1;
			}
			
			if ($mes <> date("m", strtotime($valor))) {
				$mes = number_format(date("m", strtotime($valor)));	
				$cantida_total_meses = $cantida_total_meses + 1;
				$dias = 1;
				$cantidad_dias = 1;
			}
			
			$meses_gasto[$cantida_total_meses][0] = $anho;
			$meses_gasto[$cantida_total_meses][1] = $mes;
			$meses_gasto[$cantida_total_meses][2] = $cantidad_dias;
		}
	}
	
	return $meses_gasto;
}

/**
 * ============================================================
 * 🧮 CÁLCULO DE MÁXIMOS (MES / AÑO)
 * ============================================================
 * función que genera lista de días entre fechas.
 * Retorna:
 * [0] → Máximo en un mes
 * [1] → Máximo en un año
 * [2] → Detalle por mes
 */
function calcular_maximos($lista_dias, $tipo_dias) {
	$resultado = array();
	$meses_gasto = array();
	$cantida_total_meses = 0;
	$maximo_mes = 0;
	$maximo_anho = 0;
	$suma_mes = 0;
	$suma_anho = 0;
	$mes = 0;
	$anho = 0;
	$corridos = $tipo_dias;
	$mes_registrado = 0;
	$feriados = lista_feriados();
	foreach ($lista_dias as $valor) {
		if (((date('w', strtotime($valor)) != 6) and (date('w', strtotime($valor)) != 0) and array_search($valor, $feriados, true) === FALSE) OR $corridos == 1) {
			if ($anho == 0) {
				$cantida_total_meses = $cantida_total_meses + 1;
				$mes_registrado = $cantida_total_meses;
				$anho = date("Y", strtotime($valor));
				$mes = date("m", strtotime($valor));
				$suma_anho = $suma_anho + 1;
				$maximo_anho = 0;
				$suma_mes = $suma_mes + 1;
				$maximo_mes = 0;
			} else {
				if ($anho == date("Y", strtotime($valor))) {
					if ($mes == date("m", strtotime($valor))) {
						$suma_mes = $suma_mes + 1;	
					} else {
						$cantida_total_meses = $cantida_total_meses + 1;
						$suma_mes = 0;
						$mes = date("m", strtotime($valor));
						$suma_mes = $suma_mes + 1;
					}
					
					$suma_anho = $suma_anho + 1;
				} else {
					$cantida_total_meses = $cantida_total_meses + 1;
					$meses_gasto[$cantida_total_meses][0] = $anho;
					$meses_gasto[$cantida_total_meses][1] = $mes;
					$meses_gasto[$cantida_total_meses][2] = $maximo_mes;
					$cantidad_anhos = $cantidad_anhos + 1;
					$cantidad_meses = $cantidad_meses + 1;
					$suma_anho = 0;
					$suma_mes = 0;
					$anho = date("Y", strtotime($valor));
					$mes = date("m", strtotime($valor));
					$suma_anho = $suma_anho + 1;
					$suma_mes = $suma_mes + 1;
				}
			}
			
			if ($mes_registrado != $cantida_total_meses) {
				$meses_gasto[$cantida_total_meses][0] = $anho;
				$meses_gasto[$cantida_total_meses][1] = $mes_registrado;
				$fecha_final = $anho . "-" . $mes . "-" . "01";
				$cantidad_maxima_mes = date("t", strtotime($fecha_final));
				$meses_gasto[$cantida_total_meses][2] = $cantidad_maxima_mes;
				$mes_registrado = $cantida_total_meses;
			}
			
			if ($maximo_anho < $suma_anho) {
				$maximo_anho = $suma_anho;
			}
			
			if ($maximo_mes < $suma_mes) {
				$maximo_mes = $suma_mes;
				$meses_gasto[$cantida_total_meses][0] = $anho;
				$meses_gasto[$cantida_total_meses][1] = $mes;
				$meses_gasto[$cantida_total_meses][2] = $maximo_mes;	
			}
		}
		
	}
	
	$resultado[0] = $maximo_mes;
	$resultado[1] = $maximo_anho;
	$resultado[2] = gasto_dias($lista_dias, $tipo_dias);
	
	return $resultado;
}



$resultado_maximo = array();

// Generar lista de días del permiso solicitado
$lista_dias = lista_dias($values['fecha_desde'], $values['fecha_hasta']);

// Calcular consumo
$resultado_maximo = calcular_maximos($lista_dias, $tip_dias);


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE FERIADOS/FIN DE SEMANA
 * - Valida que un permiso solicitado no sea en feriado o 
 * fin de semana.
 * ============================================================
 */
if (count($resultado_maximo[2]) <= 0) {
	$message = generarMensajeError(
		"No se pudo registrar la solicitud.",
		"Las fechas seleccionadas deben corresponder a días laborables.",
		[
			"<strong>Los permisos del tipo '$tip_descripcion', solo pueden solicitarse en días laborables.</strong>",
			"<strong>Las fechas ingresadas coinciden con feriados, sábados o domingos.</strong>",
			"<strong>Por favor, selecciona una fecha laboral válida.</strong>"
		],
		"<br><b>Verifica las fechas ingresadas e intenta nuevamente.</b>"
	);
	return false;
}
/**
 * ============================================================
 * 🚫 FIN DE VALIDACIÓN DE FERIADOS/FIN DE SEMANA
 * ============================================================
 */


foreach ($resultado_maximo[2] as $valores_mes) {
	if ($valores_mes[1] == 1){
		$desc_mes = "Enero";
	} else if($valores_mes[1] == 2) {
		$desc_mes = "Febrero";
	} else if($valores_mes[1] == 3) {
		$desc_mes = "Marzo";
	} else if($valores_mes[1] == 4) {
		$desc_mes = "Abril";
	} else if($valores_mes[1] == 5) {
		$desc_mes = "Mayo";
	} else if($valores_mes[1] == 6) {
		$desc_mes = "Junio";
	} else if($valores_mes[1] == 7) {
		$desc_mes = "Julio";
	} else if($valores_mes[1] == 8) {
		$desc_mes = "Agosto";
	} else if($valores_mes[1] == 9) {
		$desc_mes = "Septiembre";
	} else if($valores_mes[1] == 10) {
		$desc_mes = "Octubre";
	} else if($valores_mes[1] == 11) {
		$desc_mes = "Noviembre";
	} else if($valores_mes[1] == 12) {
		$desc_mes = "Diciembre";
	}
}


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE MENSUAL
 * ============================================================
 */
if ($resultado_maximo[0] > $tip_cantidad_maxima_mes) {
	/**
	 * ============================================================
	 * 🚫 VALIDACIÓN 1:
	 * La solicitud actual NO puede exceder por sí sola
	 * el máximo mensual permitido.
	 * ============================================================
	 */
	$diasSolicitados = $resultado_maximo[0];
	$message = generarMensajeError(
		"No se pudo registrar la solicitud.",
		"La cantidad de días solicitados supera el máximo permitido para este tipo de permiso.",
		[
			"<strong>Tipo de permiso: $tip_descripcion</strong>",
			"<strong>El máximo de días permitidos por mes para este tipo de permiso es de: $tip_cantidad_maxima_mes</strong>",
			"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>"
		],
		"<br><b>Reduce la cantidad de días seleccionados e intenta nuevamente.</b>"
	);
	return false;
} else {
	foreach ($resultado_maximo[2] as $valores_mes) {
		/**
		* ============================================================
		* 🚫 VALIDACIÓN 2:
		* Validar acumulado histórico del funcionario en el mes.
		* Se suma:
		* - días ya utilizados
		* - días de la nueva solicitud
		*
		*
		*	🔁 VALIDACIÓN CONTRA HISTORIAL (BD)
		*	- Suma lo ya utilizado + lo solicitado
		* ============================================================
		*/
		$sql_total_meses = "SELECT COALESCE(SUM(det_dias_gastados), 0) AS total_dias
														FROM (
																SELECT *, 
																		(SELECT tip_cod_tipo_sumatoria FROM tipos_ocurrencias WHERE tip_cod = ocu_tipo) AS ocu_cod_tipo_sumatoria
																FROM ocurrencias
																	JOIN detalle_ocurrencias ON ocu_cod = det_cod_ocurrencia
															) AS novedades
														WHERE (ocu_tipo = " . $motivo_id . " OR ocu_cod_tipo_sumatoria = " . $motivo_id . ")
														AND det_anho_gasto = " . $valores_mes[0]."
														AND det_mes_gasto = " . $valores_mes[1]."
														AND det_cod_persona = " . $values['id_funcionario']."";
		$resultado_total_meses = CustomQuery($sql_total_meses); // Deprecado
		$fila_total_mes = db_fetch_array($resultado_total_meses);
		
		// ⛔ Validar contra límite
		if ($tip_cantidad_maxima_mes < ($fila_total_mes["total_dias"] + $valores_mes[2])) {
			$diasYaUtilizados = $fila_total_mes["total_dias"];
			$diasSolicitados = $valores_mes[2];
			$totalFinal = $diasYaUtilizados + $diasSolicitados;
			$message = generarMensajeError(
				"No se pudo registrar la solicitud.",
				"El permiso solicitado supera el límite mensual permitido para '$tip_descripcion'.",
				[
					"<strong>El máximo de días permitidos por mes para este tipo de permiso es de: $tip_cantidad_maxima_mes</strong>",
					"<strong>La cantidad de días ya utilizados en $desc_mes es de: $diasYaUtilizados</strong>",
					"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>",
					"<strong>El total acumulado ya es de: $totalFinal días</strong>"
				],
				"<br><b>Reduce la cantidad de días solicitados o verifica tus permisos anteriores.</b>"
			);

			return false;
		}
	}
}
/**
 * ============================================================
 * 🚫 FIN DE VALIDACIÓN DE LÍMITE MENSUAL
 * ============================================================
 */



/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE ANUAL
 * ============================================================
 */
$cantidad_anhos = 0;
$anho_actual = 0;
$lista_anhos_valores = array();
$valor_anho = array();

// consulta acumulada anual
foreach ($resultado_maximo[2] as $valores_anho) {
	if ($anho_actual == 0) {
		$anho_actual = $valores_anho[0];
	}
	
	if ($anho_actual != $valores_anho[0]) {
		$valor_anho[1] = $cantidad_anhos;
		$valor_anho[0] = $anho_actual;
		array_push($lista_anhos_valores, $valor_anho);
		$valor_anho = array();
	} else {
		$cantidad_anhos = $valores_anho[2];
	}
}		
$valor_anho[1] = $cantidad_anhos;
$valor_anho[0] = $anho_actual;
array_push($lista_anhos_valores, $valor_anho);
foreach($lista_anhos_valores as $gastados_anho) {
	$sql_suma = "SELECT COALESCE(SUM(det_dias_gastados), 0) AS suma_anho
									FROM (
										SELECT *, 
												(SELECT tip_cod_tipo_sumatoria FROM tipos_ocurrencias WHERE tip_cod = ocu_tipo) AS ocu_cod_tipo_sumatoria
										FROM ocurrencias
											JOIN detalle_ocurrencias ON ocu_cod = det_cod_ocurrencia
									) AS novedades
									WHERE (ocu_tipo = ".$motivo_id." OR ocu_cod_tipo_sumatoria = ".$motivo_id.")
									AND det_anho_gasto = ".$valores_mes[0]."
									AND det_cod_persona = ".$values['id_funcionario']."";
	$resultado_suma = CustomQuery($sql_suma);
	$fila_suma = db_fetch_array($resultado_suma);
	if (($fila_suma['suma_anho'] + $gastados_anho[1]) > $tip_cantidad_maxima_anho) {
		$diasConsumidos = $fila_suma['suma_anho'];
		$diasSolicitados = $gastados_anho[1];
		$totalAnual = $diasConsumidos + $diasSolicitados;
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El permiso solicitado supera el límite anual permitido para '$tip_descripcion'.",
			[
				"<strong>El máximo de días permitidos por año para este tipo de permiso es de: $tip_cantidad_maxima_anho</strong>",
				"<strong>La cantidad de días ya utilizados en el año ".$gastados_anho[0]." es de: $diasConsumidos</strong>",
				"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>",
				"<strong>El total acumulado anual ya es de: $totalAnual días</strong>"
			],
			"<br><b>Verifica tus permisos utilizados durante el año.</b>"
		);
		return false;

	}
}
/**
 * ============================================================
 * 🚫 FIN DE VALIDACIÓN DE LÍMITE ANUAL
 * ============================================================
 */
$_SESSION['lista_anhos_valores'] = $resultado_maximo[2];



/**
 * ============================================================
 * 🚫 VALIDACIÓN DE GÉNERO DEL FUNCIONARIO
 * Si el $tip_genero_permitido existe y es distinto del 
 * valor 'AMBOS', el permiso se debe validar con el sexo 
 * del funcionario que esta queriendo cargar el registro.
 * ============================================================
 */
if ( !empty($tip_genero_permitido) && $tip_genero_permitido <> 'AMBOS' ) {
	$sexoFuncionario = $values["sex_descripcion"];
	if ($tip_genero_permitido != $sexoFuncionario) {
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El tipo de permiso seleccionado posee restricción de género.",
			[
				"<strong>Tipo de permiso: $tip_descripcion</strong>",
				"<strong>Este permiso solo puede ser solicitado por funcionarios del género: $tip_genero_permitido</strong>"
			],
			"<br><b>Verifica el tipo de permiso seleccionado.</b>"
		);
		return false;
	}
}
/**
 * ============================================================
 * 🚫 FIN VALIDACIÓN DE GÉNERO
 * ============================================================
 */



/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE DE TIEMPO DE PRESENTACION A DGTH
 *
 * Si el tipo de permiso tiene $tip_presentacion_cantidad 
 * entonces el permiso tiene límite de presentación y se debe 
 * validar.
 * ============================================================
 */
if ( isset($tip_presentacion_cantidad) && intval($tip_presentacion_cantidad) > 0 ) {
	
	// FECHA/HORA DEL EVENTO
	$fecha_desde_datetime = new DateTime($values["fecha_desde"]);
	$fecha_desde = $fecha_desde_datetime->format('Y-m-d') . ' '. $values["hora_desde"];
	$fechaHoraEvento = new DateTime($fecha_desde);
	
	// FECHA/HORA ACTUAL
	$fechaHoraActual = new DateTime();
	
	// DIFERENCIA EN SEGUNDOS
	$diferenciaSegundos = $fechaHoraActual->getTimestamp() - $fechaHoraEvento->getTimestamp();
	
	// CONVERTIR A HORAS
	$horasTranscurridas = $diferenciaSegundos / 3600;
	
	// VALIDAR LÍMITE
	if ( intval($horasTranscurridas) > intval($tip_presentacion_cantidad) ) {
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El tiempo máximo de presentación a DGTH fue excedido.",
			[
				"<strong>Tipo de permiso: $tip_descripcion</strong>",
				"<strong>Tiempo máximo permitido: ". $tip_presentacion_cantidad . " horas</strong>",
				"<strong>Tiempo transcurrido: ". intval($horasTranscurridas) . " horas</strong>"
			],
			"<br><b>La solicitud ya excede el tiempo permitido de presentación.</b>"
		);

		return false;
	}
	
}
/**
 * ============================================================
 * 🚫 FIN VALIDACIÓN DE PRESENTACIÓN A DGTH
 * ============================================================
 */


return true;



;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		/******************************************************************************************
 * EVENTO: Before record updated (Edit Page)
 * MÓDULO: Permisos de Funcionarios
 *
 * PROPÓSITO:
 * Este evento se ejecuta antes de actualizar un permiso.
 * Se utiliza para:
 *
 * 1. Validar datos obligatorios del perfil del funcionario
 * 2. Validar campos requeridos del formulario
 * 3. Controlar la lógica de corrección de permisos rechazados por RRHH
 *
 * REGLA DE NEGOCIO CLAVE:
 * - Si un permiso es RECHAZADO por RRHH:
 *      → El funcionario puede corregirlo SOLO UNA VEZ
 *      → Se controla mediante el campo: intentos_correccion
 * - Luego de corregir:
 *      → El estado vuelve a "PENDIENTE"
 *      → El flujo reinicia
 *
 * NOTA:
 * - $values = nuevos valores del formulario
 * - $oldvalues = valores actuales en la base de datos
 * - return false = cancela el guardado
 ******************************************************************************************/

/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
//function debug_to_console($data, $context = 'Debug in Console') {
//	ob_start();
//	$output  = 'console.info(\'' . $context . ':\');';
//	$output .= 'console.log(' . json_encode($data) . ');';
//	$output  = sprintf('<script>%s</script>', $output);
//	echo $output;
//}

/*==============================================================
=        FUNCIÓN PARA GENERAR MENSAJES DE ERROR VISUAL        =
==============================================================*/
/**
 * Genera un bloque HTML estilizado para mostrar errores al usuario.
 * Permite incluir:
 * @param string $titulo
 * @param string $descripcion
 * @param array  $items Lista opcional de campos faltantes
 * @param string $footer Texto adicional (ej: instrucciones)
 */
function generarMensajeError($titulo, $descripcion, $items = [], $footer = "") {
	$htmlItems = "";
	
	if (!empty($items)) {
		$htmlItems .= "<ul style='margin-top:8px'>";
		foreach ($items as $item) {
			$htmlItems .= "<li>$item</li>";
		}
		$htmlItems .= "</ul>";
	}
	
	return "
	<div style='
		background:#f8d7da;
		color:#721c24;
		padding:14px;
		border-radius:12px;
		border-left:6px solid #dc3545;
	'>
		<b>❌ $titulo</b>
		<br><br>
		<b>$descripcion</b>
		$htmlItems
		$footer
	</div>";
}


/**
 * ============================================================
 * 👤 VALIDACIÓN DE DATOS DEL PERFIL DEL FUNCIONARIO
 * ============================================================
 * Se valida que el funcionario tenga datos básicos completos.
 * Estos datos NO se cargan en el formulario directamente,
 * pero son necesarios para procesar correctamente el permiso.
 * Verifica que el usuario tenga completos los datos básicos
 * antes de permitir enviar una solicitud.
 */
// (descripcion_tipo_vinculacion: es de solo lectura(READONLY) por eso no se envia por POST, solucion provisoria enviar el descripcion_dependencia_edit).
$camposRequeridosPerfil = [
	"descripcion_dependencia_edit" => "Dependencia",
	//"descripcion_tipo_vinculacion" => "Tipo de vinculación"
	"tipo_vinculacion" => "Tipo de vinculación"
];

$faltantesPerfil = [];

foreach ($camposRequeridosPerfil as $campo => $label) {
	if (!isset($values[$campo]) || trim($values[$campo]) === "") {
		$faltantesPerfil[] = $label;
	}
}

// ⛔ Si faltan datos → detener proceso
if (!empty($faltantesPerfil)) {
	$message = generarMensajeError(
		"No es posible enviar la solicitud de permiso.",
		"Faltan completar los siguientes datos de tu perfil:",
		$faltantesPerfil,
		"Por favor, comunícate con el área de <b>Recursos Humanos</b> para actualizar tu información."
	);
	
	return false; // ⛔ DETIENE TODO
}
// FIN VALIDACIÓN DE PERFIL DEL FUNCIONARIO



/**
 * ============================================================
 * 📝 VALIDACIÓN DE CAMPOS DEL FORMULARIO
 * ============================================================
 * Verifica que todos los campos obligatorios estén completos.
 */
$camposRequeridosFormulario = [
	"motivo_id" => "Tipo de permiso o justificación",
	"fecha_desde" => "Fecha desde",
	"hora_desde" => "Hora de inicio",
	"fecha_hasta" => "Fecha hasta",
	"hora_hasta" => "Hora de fin",
	"email_jefe_id" => "Correo electrónico del superior inmediato"
];

$faltantesFormulario = [];

foreach ($camposRequeridosFormulario as $campoForm => $labelForm) {
	if (!isset($values[$campoForm]) || trim($values[$campoForm]) === "") {
		$faltantesFormulario[] = $labelForm;
	}
}

// ⛔ Si faltan datos → detener proceso
if (!empty($faltantesFormulario)) {
	$message = generarMensajeError(
		"No es posible enviar la solicitud de permiso.",
		"Falta completar los siguientes datos del formulario:",
		$faltantesFormulario,
		"Por favor, completa los campos obligatorios del formulario."
	);

	return false; // ⛔ DETIENE TODO
}
// FIN VALIDACIÓN DE CAMPOS DEL FORMULARIO



$motivo_id = $values["motivo_id"];
//debug_to_console("motivo_id: " . $motivo_id);

// Obtener la descripcion del tipo de permiso para un mensaje más claro para el usuario.
$sqlMotivoDesc = "SELECT * 
											FROM public.tipos_ocurrencias 
											WHERE tip_cod = $motivo_id";
$rsMotivoDesc = DB::Query($sqlMotivoDesc);
$dataMotivoDesc = $rsMotivoDesc->fetchAssoc();
$tip_descripcion = $dataMotivoDesc["tip_descripcion"];
$tip_dias = $dataMotivoDesc["tip_dias"];
$tip_cantidad_maxima_mes = $dataMotivoDesc["tip_cantidad_maxima_mes"];
$tip_cantidad_maxima_anho = $dataMotivoDesc["tip_cantidad_maxima_anho"];
$tip_presentacion_cantidad = $dataMotivoDesc["tip_presentacion_cantidad"];
$tip_genero_permitido = $dataMotivoDesc["tip_genero_permitido"];
debug_to_console("tip_descripcion: " . $tip_descripcion . ", tip_dias: " . $tip_dias . ", tip_cantidad_maxima_mes: " . $tip_cantidad_maxima_mes . ", tip_cantidad_maxima_anho: " . $tip_cantidad_maxima_anho);


/**
 * ============================================================
 * 📅 FUNCIONES AUXILIARES DE FECHAS
 * ============================================================
 */

/**
 * Funcion que calcula dias entre fechas.
 * Genera un array con todas las fechas entre inicio y fin
 */
function lista_dias($inicio, $fin) {
	$rango = array();
	if (is_string($inicio) === true) $inicio = strtotime($inicio);
	if (is_string($fin) === true ) $fin = strtotime($fin);
	if ($inicio > $fin) return createDateRangeArray($fin, $inicio);
	
	do {
		$rango[] = date('Y-m-d', $inicio);
		$inicio = strtotime("+ 1 day", $inicio);
	} while($inicio <= $fin);
	
	return $rango;
}

/**
 * Obtiene lista de feriados desde BD
 */
function lista_feriados() {
	$lista_feriados = array();
	$sql_feriados = "select fer_fecha from feriados";
	$resultado_feriados = CustomQuery($sql_feriados);
	while($feriado = db_fetch_array($resultado_feriados)) {
		array_push($lista_feriados, $feriado['fer_fecha']);
	}
	return $lista_feriados;
}

/**
 * ============================================================
 * 📊 CÁLCULO DE DÍAS UTILIZADOS
 * ============================================================
 * Calcula días consumidos considerando:
 * - Fines de semana
 * - Feriados
 * - Tipo de días (corridos o hábiles)
 */
function gasto_dias($lista_dias, $tipo_dias) {	
	$resultado = array();
	$meses_gasto = array();
	$cantida_total_meses = 0;
	$mes = 0;
	$anho = 0;
	$dias = 0;
	$cantidad_dias = 0;
	$corridos = $tipo_dias;
	$feriados = lista_feriados();
	
	foreach ($lista_dias as $valor) {
		if (((date('w', strtotime($valor)) != 6) and (date('w', strtotime($valor)) != 0) and array_search($valor, $feriados, true) === FALSE ) OR $corridos == 1) {	
			$dias = $dias + 1;
			$cantidad_dias = $dias;
			if ($anho == 0 or $anho <> date("Y", strtotime($valor))) {
				$anho = date("Y", strtotime($valor));
				$mes = number_format(date("m", strtotime($valor)));
				$cantida_total_meses = $cantida_total_meses + 1;
				$dias = 1;
			}
			
			if ($mes <> date("m", strtotime($valor))) {
				$mes = number_format(date("m", strtotime($valor)));	
				$cantida_total_meses = $cantida_total_meses + 1;
				$dias = 1;
				$cantidad_dias = 1;
			}

			$meses_gasto[$cantida_total_meses][0] = $anho;
			$meses_gasto[$cantida_total_meses][1] = $mes;
			$meses_gasto[$cantida_total_meses][2] = $cantidad_dias;
		}
	}
	
	return $meses_gasto;
}


/**
 * ============================================================
 * 🧮 CÁLCULO DE MÁXIMOS (MES / AÑO)
 * ============================================================
 * función que genera lista de días entre fechas.
 * Retorna:
 * [0] → Máximo en un mes
 * [1] → Máximo en un año
 * [2] → Detalle por mes
 */
function calcular_maximos($lista_dias, $tipo_dias) {
	$resultado = array();
	$meses_gasto = array();
	$cantida_total_meses = 0;
	$maximo_mes = 0;
	$maximo_anho = 0;
	$suma_mes = 0;
	$suma_anho = 0;
	$mes = 0;
	$anho = 0;
	$corridos = $tipo_dias;
	$mes_registrado = 0;
	$feriados = lista_feriados();
	foreach ($lista_dias as $valor) {
		if (((date('w', strtotime($valor)) != 6) and (date('w', strtotime($valor)) != 0) and array_search($valor, $feriados, true) === FALSE) OR $corridos == 1) {
			if ($anho == 0) {
				$cantida_total_meses = $cantida_total_meses + 1;
				$mes_registrado = $cantida_total_meses;
				$anho = date("Y", strtotime($valor));
				$mes = date("m", strtotime($valor));
				$suma_anho = $suma_anho + 1;
				$maximo_anho = 0;
				$suma_mes = $suma_mes + 1;
				$maximo_mes = 0;
			} else {
				if ($anho == date("Y", strtotime($valor))) {
					if ($mes == date("m", strtotime($valor))) {
						$suma_mes = $suma_mes + 1;	
					} else {
						$cantida_total_meses = $cantida_total_meses + 1;
						$suma_mes = 0;
						$mes = date("m", strtotime($valor));
						$suma_mes = $suma_mes + 1;
					}
					
					$suma_anho = $suma_anho + 1;
				} else {
					$cantida_total_meses = $cantida_total_meses + 1;
					$meses_gasto[$cantida_total_meses][0] = $anho;
					$meses_gasto[$cantida_total_meses][1] = $mes;
					$meses_gasto[$cantida_total_meses][2] = $maximo_mes;
					$cantidad_anhos = $cantidad_anhos + 1;
					$cantidad_meses = $cantidad_meses + 1;
					$suma_anho = 0;
					$suma_mes = 0;
					$anho = date("Y", strtotime($valor));
					$mes = date("m", strtotime($valor));
					$suma_anho = $suma_anho + 1;
					$suma_mes = $suma_mes + 1;
				}
			}
			
			if ($mes_registrado != $cantida_total_meses) {
				$meses_gasto[$cantida_total_meses][0] = $anho;
				$meses_gasto[$cantida_total_meses][1] = $mes_registrado;
				$fecha_final = $anho . "-" . $mes . "-" . "01";
				$cantidad_maxima_mes = date("t", strtotime($fecha_final));
				$meses_gasto[$cantida_total_meses][2] = $cantidad_maxima_mes;
				$mes_registrado = $cantida_total_meses;
			}
			
			if ($maximo_anho < $suma_anho) {
				$maximo_anho = $suma_anho;
			}
			
			if ($maximo_mes < $suma_mes) {
				$maximo_mes = $suma_mes;
				$meses_gasto[$cantida_total_meses][0] = $anho;
				$meses_gasto[$cantida_total_meses][1] = $mes;
				$meses_gasto[$cantida_total_meses][2] = $maximo_mes;	
			}	
		}
	}
	
	$resultado[0] = $maximo_mes;
	$resultado[1] = $maximo_anho;
	$resultado[2] = gasto_dias($lista_dias, $tipo_dias);
	return $resultado;

}


$resultado_maximo = array();
/**
 * ============================================================
 * 📊 OBTENER CONFIGURACIÓN DEL PERMISO
 * ============================================================
 * Consulta cantidades de dias permitidos por permiso.
 */
//$sql_cantidades = "SELECT tip_cantidad_maxima_mes,tip_cantidad_maxima_anho,tip_dias 
//											FROM tipos_ocurrencias 
//											WHERE tip_cod = " . $motivo_id;
//debug_to_console("sql_cantidades: " . $sql_cantidades);
//$resultados_cantidades = CustomQuery($sql_cantidades);
//$fila_cantidades = db_fetch_array($resultados_cantidades);

// Generar lista de días del permiso solicitado
$lista_dias = lista_dias($values['fecha_desde'], $values['fecha_hasta']);

// Calcular consumo
//$resultado_maximo = calcular_maximos($lista_dias, $fila_cantidades['tip_dias']);
$resultado_maximo = calcular_maximos($lista_dias, $tip_dias);

//$tip_cantidad_maxima_mes = $fila_cantidades["tip_cantidad_maxima_mes"];
//$tip_cantidad_maxima_anho = $fila_cantidades["tip_cantidad_maxima_anho"];
//debug_to_console("tip_cantidad_maxima_mes: " . $tip_cantidad_maxima_mes . " tip_cantidad_maxima_anho: " . $tip_cantidad_maxima_anho);


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE FERIADOS/FIN DE SEMANA
 * - Valida que un permiso solicitado no sea en feriado o 
 * fin de semana.
 * ============================================================
 */
if (count($resultado_maximo[2]) <= 0) {
	$message = generarMensajeError(
		"No se pudo registrar la solicitud.",
		"Las fechas seleccionadas deben corresponder a días laborables.",
		[
			"<strong>Los permisos del tipo '$tip_descripcion', solo pueden solicitarse en días laborables.</strong>",
			"<strong>Las fechas ingresadas coinciden con feriados, sábados o domingos.</strong>",
			"<strong>Por favor, selecciona una fecha laboral válida.</strong>"
		],
		"<br><b>Verifica las fechas ingresadas e intenta nuevamente.</b>"
	);
	return false;
}
/**
 * ============================================================
 * 🚫 FIN DE VALIDACIÓN DE FERIADOS/FIN DE SEMANA
 * ============================================================
 */




foreach ($resultado_maximo[2] as $valores_mes) {
	//debug_to_console("valores_mes[0]: " . $valores_mes[0] . " valores_mes[1]: " . $valores_mes[1] );
	if ($valores_mes[1] == 1){
		$desc_mes = "Enero";
	} else if($valores_mes[1] == 2) {
		$desc_mes = "Febrero";
	} else if($valores_mes[1] == 3) {
		$desc_mes = "Marzo";
	} else if($valores_mes[1] == 4) {
		$desc_mes = "Abril";
	} else if($valores_mes[1] == 5) {
		$desc_mes = "Mayo";
	} else if($valores_mes[1] == 6) {
		$desc_mes = "Junio";
	} else if($valores_mes[1] == 7) {
		$desc_mes = "Julio";
	} else if($valores_mes[1] == 8) {
		$desc_mes = "Agosto";
	} else if($valores_mes[1] == 9) {
		$desc_mes = "Septiembre";
	} else if($valores_mes[1] == 10) {
		$desc_mes = "Octubre";
	} else if($valores_mes[1] == 11) {
		$desc_mes = "Noviembre";
	} else if($valores_mes[1] == 12) {
		$desc_mes = "Diciembre";
	}
}


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE MENSUAL
 * ============================================================
 */
//if ($resultado_maximo[0] > $fila_cantidades['tip_cantidad_maxima_mes']) {
if ($resultado_maximo[0] > $tip_cantidad_maxima_mes) {
	/**
	 * ============================================================
	 * 🚫 VALIDACIÓN 1:
	 * La solicitud actual NO puede exceder por sí sola
	 * el máximo mensual permitido.
	 * ============================================================
	 */
	//$message = generarMensajeError(
	//	"📋 <strong>Límite mensual alcanzado[$tip_cantidad_maxima_mes]</strong><br>",
	//	"Cantidad máxima alcanzada para el Motivo '$tip_descripcion'<br> <ul><li>La Cantidad máxima del mes para el Motivo '$tip_descripcion' es de: " . $fila_cantidades['tip_cantidad_maxima_mes'] . " </li><li> Cantidad actual: " . $resultado_maximo[0] . "</li></ul>",
	//	[]
	//);
	//return false;
	
	$diasSolicitados = $resultado_maximo[0];
	$message = generarMensajeError(
		"No se pudo registrar la solicitud.",
		"La cantidad de días solicitados supera el máximo permitido para este tipo de permiso.",
		[
			"<strong>Tipo de permiso: $tip_descripcion</strong>",
			"<strong>El máximo de días permitidos por mes para este tipo de permiso es de: $tip_cantidad_maxima_mes</strong>",
			"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>"
		],
		"<br><b>Reduce la cantidad de días seleccionados e intenta nuevamente.</b>"
	);
	return false;
	
} else {
	foreach ($resultado_maximo[2] as $valores_mes) {
		
		/**
		* ============================================================
		* 🚫 VALIDACIÓN 2:
		* Validar acumulado histórico del funcionario en el mes.
		* Se suma:
		* - días ya utilizados
		* - días de la nueva solicitud
		*
		*
		*	🔁 VALIDACIÓN CONTRA HISTORIAL (BD)
		*	- Suma lo ya utilizado + lo solicitado
		* ============================================================
		*/
		$sql_total_meses = "SELECT COALESCE(SUM(det_dias_gastados), 0) AS total_dias
														FROM (
																SELECT *, 
																		(SELECT tip_cod_tipo_sumatoria FROM tipos_ocurrencias WHERE tip_cod = ocu_tipo) AS ocu_cod_tipo_sumatoria
																FROM ocurrencias
																	JOIN detalle_ocurrencias ON ocu_cod = det_cod_ocurrencia
															) AS novedades
														WHERE (ocu_tipo = " . $motivo_id . " OR ocu_cod_tipo_sumatoria = " . $motivo_id . ")
														AND det_anho_gasto = " . $valores_mes[0]."
														AND det_mes_gasto = " . $valores_mes[1]."
														AND det_cod_persona = " . $values['id_funcionario']."";
		//debug_to_console("sql_total_meses: " . $sql_total_meses);
		$resultado_total_meses = CustomQuery($sql_total_meses); // Deprecado
		$fila_total_mes = db_fetch_array($resultado_total_meses);
		
		// ⛔ Validar contra límite
		//if ($fila_cantidades["tip_cantidad_maxima_mes"] < ($fila_total_mes["total_dias"] + $valores_mes[2])) {
		//	$message = generarMensajeError(
		//		"📋 <strong>Límite mensual alcanzado[$tip_cantidad_maxima_mes]</strong><br>",
		//		"Cantidad máxima alcanzada para el Motivo '$tip_descripcion'.<br> <ul><li>La Cantidad máxima del mes para el Motivo '$tip_descripcion' es de:  ".$tip_cantidad_maxima_mes."</il> <li>La Cantidad utilizada en el mes de ".$desc_mes." es de: ".($fila_total_mes["total_dias"]+$valores_mes[2]) . "</li></ul>",
		//		[]
		//	);
		//	return false;
		//}
		if ($tip_cantidad_maxima_mes < ($fila_total_mes["total_dias"] + $valores_mes[2])) {
			$diasYaUtilizados = $fila_total_mes["total_dias"];
			$diasSolicitados = $valores_mes[2];
			$totalFinal = $diasYaUtilizados + $diasSolicitados;
			$message = generarMensajeError(
				"No se pudo registrar la solicitud.",
				"El permiso solicitado supera el límite mensual permitido para '$tip_descripcion'.",
				[
					"<strong>El máximo de días permitidos por mes para este tipo de permiso es de: $tip_cantidad_maxima_mes</strong>",
					"<strong>La cantidad de días ya utilizados en $desc_mes es de: $diasYaUtilizados</strong>",
					"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>",
					"<strong>El total acumulado ya es de: $totalFinal días</strong>"
				],
				"<br><b>Reduce la cantidad de días solicitados o verifica tus permisos anteriores.</b>"
			);

			return false;
		}
	}
}


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE ANUAL
 * ============================================================
 */
$cantidad_anhos = 0;
$anho_actual = 0;
$lista_anhos_valores = array();
$valor_anho = array();

// consulta acumulada anual
foreach ($resultado_maximo[2] as $valores_anho) {
	if ($anho_actual == 0) {
		$anho_actual = $valores_anho[0];
	}
	
	if ($anho_actual != $valores_anho[0]) {
		$valor_anho[1] = $cantidad_anhos;
		$valor_anho[0] = $anho_actual;
		array_push($lista_anhos_valores, $valor_anho);
		$valor_anho = array();
	} else {
		$cantidad_anhos = $valores_anho[2];
	}
}		
$valor_anho[1] = $cantidad_anhos;
$valor_anho[0] = $anho_actual;
array_push($lista_anhos_valores, $valor_anho);

foreach($lista_anhos_valores as $gastados_anho) {
	$sql_suma = "SELECT COALESCE(SUM(det_dias_gastados), 0) AS suma_anho
									FROM (
										SELECT *, 
												(SELECT tip_cod_tipo_sumatoria FROM tipos_ocurrencias WHERE tip_cod = ocu_tipo) AS ocu_cod_tipo_sumatoria
										FROM ocurrencias
											JOIN detalle_ocurrencias ON ocu_cod = det_cod_ocurrencia
									) AS novedades
									WHERE (ocu_tipo = ".$motivo_id." OR ocu_cod_tipo_sumatoria = ".$motivo_id.")
									AND det_anho_gasto = ".$valores_mes[0]."
									AND det_cod_persona = ".$values['id_funcionario']."";
	$resultado_suma = CustomQuery($sql_suma);
	$fila_suma = db_fetch_array($resultado_suma);
	//if (($fila_suma['suma_anho'] + $gastados_anho[1]) > $fila_cantidades['tip_cantidad_maxima_anho']) {
	//	$valor = $fila_suma['suma_anho'] + $gastados_anho[1];
	//	$message = generarMensajeError(
	//		"📋 <strong>Límite anual alcanzado[$tip_cantidad_maxima_anho]</strong>",
	//		"<ul><li>La Cantidad máxima por año para el Motivo '$tip_descripcion' es de: ".$fila_cantidades['tip_cantidad_maxima_anho']."</il> <li>Cantidad Actual de solicitudes: ".$valor."</li></ul>",
	//		[]
	//	);
	//	return false;
	//}
	if (($fila_suma['suma_anho'] + $gastados_anho[1]) > $tip_cantidad_maxima_anho) {
		$diasConsumidos = $fila_suma['suma_anho'];
		$diasSolicitados = $gastados_anho[1];
		$totalAnual = $diasConsumidos + $diasSolicitados;
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El permiso solicitado supera el límite anual permitido para '$tip_descripcion'.",
			[
				"<strong>El máximo de días permitidos por año para este tipo de permiso es de: $tip_cantidad_maxima_anho</strong>",
				"<strong>La cantidad de días ya utilizados en el año ".$gastados_anho[0]." es de: $diasConsumidos</strong>",
				"<strong>La cantidad de días que solicitaste es de: $diasSolicitados</strong>",
				"<strong>El total acumulado anual ya es de: $totalAnual días</strong>"
			],
			"<br><b>Verifica tus permisos utilizados durante el año.</b>"
		);
		return false;

	}
}

$_SESSION['lista_anhos_valores'] = $resultado_maximo[2];


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE GÉNERO DEL FUNCIONARIO
 * Si el $tip_genero_permitido existe y es distinto del 
 * valor 'AMBOS', el permiso se debe validar con el sexo 
 * del funcionario que esta queriendo cargar el registro.
 * ============================================================
 */
if ( !empty($tip_genero_permitido) && $tip_genero_permitido <> 'AMBOS' ) {
	$sexoFuncionario = $values["sex_descripcion"];
	if ($tip_genero_permitido != $sexoFuncionario) {
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El tipo de permiso seleccionado posee restricción de género.",
			[
				"<strong>Tipo de permiso: $tip_descripcion</strong>",
				"<strong>Este permiso solo puede ser solicitado por funcionarios del género: $tip_genero_permitido</strong>"
			],
			"<br><b>Verifica el tipo de permiso seleccionado.</b>"
		);
		return false;
	}
}
/**
 * ============================================================
 * 🚫 FIN VALIDACIÓN DE GÉNERO
 * ============================================================
 */


/**
 * ============================================================
 * 🚫 VALIDACIÓN DE LÍMITE DE TIEMPO DE PRESENTACION A DGTH
 *
 * Si el tipo de permiso tiene $tip_presentacion_cantidad 
 * entonces el permiso tiene límite de presentación y se debe 
 * validar.
 * ============================================================
 */
if ( isset($tip_presentacion_cantidad) && intval($tip_presentacion_cantidad) > 0 ) {
	
	// FECHA/HORA DEL EVENTO
	$fecha_desde_datetime = new DateTime($values["fecha_desde"]);
	$fecha_desde = $fecha_desde_datetime->format('Y-m-d') . ' '. $values["hora_desde"];
	$fechaHoraEvento = new DateTime($fecha_desde);
	
	// FECHA/HORA ACTUAL
	$fechaHoraActual = new DateTime();
	
	// DIFERENCIA EN SEGUNDOS
	$diferenciaSegundos = $fechaHoraActual->getTimestamp() - $fechaHoraEvento->getTimestamp();
	
	// CONVERTIR A HORAS
	$horasTranscurridas = $diferenciaSegundos / 3600;
	
	// VALIDAR LÍMITE
	if ( intval($horasTranscurridas) > intval($tip_presentacion_cantidad) ) {
		$message = generarMensajeError(
			"No se pudo registrar la solicitud.",
			"El tiempo máximo de presentación a DGTH fue excedido.",
			[
				"<strong>Tipo de permiso: $tip_descripcion</strong>",
				"<strong>Tiempo máximo permitido: ". $tip_presentacion_cantidad . " horas</strong>",
				"<strong>Tiempo transcurrido: ". intval($horasTranscurridas) . " horas</strong>"
			],
			"<br><b>La solicitud ya excede el tiempo permitido de presentación.</b>"
		);

		return false;
	}
	
}
/**
 * ============================================================
 * 🚫 FIN VALIDACIÓN DE PRESENTACIÓN A DGTH
 * ============================================================
 */







/*==============================================================
=        LÓGICA DE CORRECCIÓN DE PERMISOS RECHAZADOS         =
==============================================================*/
/**
 * Este bloque controla el comportamiento cuando el permiso
 * fue previamente RECHAZADO por RRHH(DGTH).
 *
 * ESCENARIO:
 * - El funcionario edita un permiso rechazado
 *
 * ACCIONES:
 * - Se incrementa el contador de correcciones
 * - Se cambia el estado a PENDIENTE (reinicia flujo)
 * - Se actualiza el motivo de rechazo
 * - Se evita reenviar correo al jefe
 */
if ($oldvalues["rrhh_resultado_decision"] == 'RECHAZADO') {
	
	// Incrementar contador de correcciones
	$values["intentos_correccion"] = $oldvalues["intentos_correccion"] + 1;
    
	// Volver a estado pendiente para que pase otra vez por flujo
	// Reiniciar flujo → vuelve a pendiente
	$values["rrhh_resultado_decision"] = 'PENDIENTE';
	// Mensaje interno de control (ya no es rechazo real)
	$values["rrhh_motivo_rechazo"] = $oldvalues["rrhh_motivo_rechazo"];
	// No reenviar correo al jefe (ya fue enviado anteriormente)
	$enviar_mail_jefe = 0;
} else {
	/**
	 * ESCENARIO:
	 * - Edición normal (permiso aún no rechazado)
	 *
	 * ACCIONES:
	 * - Mantener valores actuales sin alterar lógica de corrección
	 */
	
	// Mantener valor actual de intentos si no viene en el formulario
	if(!isset($values["intentos_correccion"])) {
		$values["intentos_correccion"] = $oldvalues["intentos_correccion"];
	}
	
	// Mantener motivo de rechazo existente (si aplica)
	$values["rrhh_motivo_rechazo"] = $oldvalues["rrhh_motivo_rechazo"];
	// Enviar correo al jefe (flujo normal)
	$enviar_mail_jefe = 1;
}


/*==============================================================
=        FINALIZACIÓN DEL EVENTO                             =
==============================================================*/
/**
 * Si todas las validaciones pasan correctamente,
 * se permite continuar con el proceso de actualización.
 */
return true;


;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		
/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Imprime información en la consola del navegador.
 * Útil SOLO en desarrollo para verificar valores.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Texto descriptivo del contexto
 */
function debug_to_console($data, $context = 'Debug in Console') {
	ob_start();
	$output  = 'console.info(\'' . $context . ':\');';
	$output .= 'console.log(' . json_encode($data) . ');';
	$output  = sprintf('<script>%s</script>', $output);
	echo $output;
}

// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || '  ' || p.per_apellido AS nombre_completo,
																p.per_cod,
																p.tipo_funcionario_tfun_cod,
																tf.tfun_descri AS descripcion_tipo_funcionario,
																TO_CHAR(AGE(CURRENT_DATE, p.per_ingreso), 'YY \"años, \" MM \"meses y \" DD \"días\"') AS antiguedad_laboral,
																c.car_descri,
																s.sed_descripcion
												FROM personales p
													LEFT JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
													LEFT JOIN tipo_funcionario tf ON tf.tfun_cod = p.tipo_funcionario_tfun_cod
													LEFT JOIN cargos c ON c.car_cod = p.cargos_car_cod
													LEFT JOIN sedes s ON s.sed_cod = p.per_sede
												WHERE p.per_cod = $userPersonal";
//debug_to_console("sqlDependencia: " . $sqlDependencia);
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);
$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);
$pageObject->setProxyValue("tipo_funcionario_tfun_cod", $dataDependencia["tipo_funcionario_tfun_cod"]);
$pageObject->setProxyValue("descripcion_tipo_funcionario", $dataDependencia["descripcion_tipo_funcionario"]);
$pageObject->setProxyValue("antiguedad_laboral", $dataDependencia["antiguedad_laboral"]);
$pageObject->setProxyValue("car_descri", $dataDependencia["car_descri"]);
$pageObject->setProxyValue("sed_descripcion", $dataDependencia["sed_descripcion"]);


// Query para obtener el conteo de cantidad de permisos por mes.
$sqlTotalPermisos = DB::PrepareSQL(
"SELECT TO_CHAR(fecha_solicitud, 'TMMonth') AS mes_nombre, 
				COUNT(*) AS cantidad_permisos_mes
FROM rrhh_permisos.permisos_funcionarios
WHERE id_funcionario = ':1'
  AND EXTRACT(MONTH FROM fecha_solicitud) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND EXTRACT(YEAR FROM fecha_solicitud) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY TO_CHAR(fecha_solicitud, 'TMMonth')", $userPersonal
);
//debug_to_console("sqlTotalPermisos: " . $sqlTotalPermisos);
$resultTotalPermisos = DB::Query($sqlTotalPermisos);
$rowTotalPermisos = $resultTotalPermisos->fetchAssoc();
if ($rowTotalPermisos && $rowTotalPermisos['cantidad_permisos_mes'] > 0) {
	$cantidad_permisos_mes = $rowTotalPermisos['cantidad_permisos_mes'];
} else {
	$cantidad_permisos_mes = 0;
}
//debug_to_console("mes_nombre: " . $rowTotalPermisos['mes_nombre'] . ", total_permisos: " . $rowTotalPermisos['cantidad_permisos_mes']);
$pageObject->setProxyValue("cantidad_permisos_mes", $cantidad_permisos_mes);

// Oculta el id de permiso de el formulario.
$pageObject->hideItem("view_id");

//debug_to_console("id: " . $values["id"]);

// Calcular la cantidad de días entre dos fechas.
$sqlTotalDias = DB::PrepareSQL(
"SELECT id,
    id_funcionario,
    fecha_desde,
    fecha_hasta,
    (fecha_hasta - fecha_desde) AS dias_diferencia,
    (fecha_hasta - fecha_desde) + 1 AS dias_totales
FROM rrhh_permisos.permisos_funcionarios
WHERE permisos_funcionarios.id = ':1'", $values["id"]
);
//debug_to_console("sqlTotalDias: " . $sqlTotalDias);
$resultTotalDias = DB::Query($sqlTotalDias);
$rowTotalDias = $resultTotalDias->fetchAssoc();
// Voy a usar la columna de 'dias_totales' porque la columna de 'dias_diferencia', si
// el permiso es en el dia muestra cero(0), y para evitar confusiones al usuario 
// uso esa columna del query. 
$dias_totales = $rowTotalDias['dias_totales'];

//debug_to_console("dias_totales: " . $dias_totales);
$pageObject->setProxyValue("dias_totales", $dias_totales);

;		
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
