<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_solicitudes_vacaciones  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowAdd"]=true;


		$this->events["CustomAdd"]=true;


		$this->events["CustomEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		/*****************************************************************
 * EVENTO: Before Display (ADD)
 * MÓDULO: Solicitudes de Vacaciones
 * DESCRIPCIÓN:
 *  - Oculta campos técnicos y de auditoría
 *  - Evita que el usuario modifique datos de sistema
 *  - Estos valores se asignan automáticamente en backend
 *****************************************************************/

/*==============================================================
=            CAMPOS DE CONTROL DE ESTADO                       =
==============================================================*/

// Estado de la solicitud (se inicializa como "PENDIENTE" en backend)
$pageObject->hideItem("add_estado");//oculta el campo estado

// Fecha de creación del registro (asignada automáticamente)
$pageObject->hideItem("add_fecha_creacion");//oculta el campo fecha_creacion

// Usuario que crea la solicitud (usuario logueado)
$pageObject->hideItem("add_usuario_creador");//oculta el campo usuario_creador

// ID primario del registro (se genera automáticamente)
$pageObject->hideItem("add_id");//oculta el campo id
// ID interno del funcionario (se obtiene por la cédula)
$pageObject->hideItem("add_id_funcionario");//oculta el campo id_funcionario

// Fecha de última actualización (uso interno del sistema)
$pageObject->hideItem("add_fecha_actualizacion");//oculta el campo fecha_actualizacion

// Usuario que realizó la última actualización
$pageObject->hideItem("add_usuario_actualizacion");//oculta el campo usuario_actualizacion


$pageObject->hideItem("add_dependencia_id");


// Obtener datos del usuario logueado en PHPRunner
$currentUser = Security::currentUserData();

// ID del usuario logueado (tabla users de PHPRunner)
$userPersonal = $currentUser["usu_personal"];

// Obtener Dependencia y datos de la persona logueada.
$sqlDependencia = "SELECT d.dep_descripcion || ' - ' || d.dep_descripcion_corta AS descripcion_dependencia,
																p.per_ci AS persona_ci,
																d.dep_cod,
																p.per_nombre || ' - ' || p.per_apellido AS nombre_completo,
																p.per_cod
												FROM personales p
													JOIN dependencias d ON d.dep_cod = p.dependencias_dep_cod
												WHERE p.per_cod = $userPersonal";
$resultDependencia = CustomQuery($sqlDependencia);
$dataDependencia = db_fetch_array($resultDependencia);
$pageObject->setProxyValue("dep_cod", $dataDependencia["dep_cod"]);
$pageObject->setProxyValue("descripcion_dependencia", $dataDependencia["descripcion_dependencia"]);
$pageObject->setProxyValue("persona_ci", $dataDependencia["persona_ci"]);
$pageObject->setProxyValue("nombre_completo", $dataDependencia["nombre_completo"]);
$pageObject->setProxyValue("per_cod", $dataDependencia["per_cod"]);



;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		/**************************************************************
 * EVENTO: Custom Add
 * MÓDULO: Solicitudes de Vacaciones
 * DESCRIPCIÓN:
 *  - Inserta una nueva solicitud de vacaciones
 *  - Calcula y almacena los días hábiles solicitados
 *  - Inicializa la solicitud en estado "PENDIENTE"
 **************************************************************/


/*==============================================================
=            FUNCIÓN AUXILIAR PARA DEPURACIÓN                  =
==============================================================*/
/**
 * Envía información a la consola del navegador.
 * Útil únicamente durante el desarrollo.
 *
 * @param mixed  $data    Datos a mostrar
 * @param string $context Contexto del mensaje
 */
function debug_to_console($data, $context = 'Debug in Console') {
	ob_start();
	$output  = 'console.info(\'' . $context . ':\');';
	$output .= 'console.log(' . json_encode($data) . ');';
	$output  = sprintf('<script>%s</script>', $output);
	echo $output;
}
	
	
/*==============================================================
=            DATOS DEL USUARIO LOGUEADO                        =
==============================================================*/

// Obtener datos del usuario actualmente autenticado
$currentUserData = Security::currentUserData();
	
/*==============================================================
=            OBTENCIÓN DE VALORES DEL FORMULARIO               =
==============================================================*/
/**
 * $values contiene los campos enviados desde el formulario ADD
 */
$dependencia_id = $values["dependencia_id"];
$per_ci = $values["per_ci"];
$id_funcionario = $values["id_funcionario"];
$fecha_desde = $values["fecha_desde"];
$fecha_hasta = $values["fecha_hasta"];
$total_dias_habiles = $values["total_dias_habiles"];
$observacion = $values["observacion"];
$tipo_vinculacion = $values["tipo_vinculacion"];
$nombre_completo = $values["nombre_completo"];
$estado = "PENDIENTE"; // Estado inicial de la solicitud
$fecha_creacion = $values["fecha_creacion"]; // Fecha de creación del registro
$usuario_creador = $currentUserData["usu_cod"];
$nombreDependencia = $values["descripcion_dependencia"];

/*==============================================================
=            INSERCIÓN DE SOLICITUD DE VACACIONES              =
==============================================================*/
$sqlInsertSolicitudesVacaciones = DB::PrepareSQL(
	"INSERT INTO rrhh_permisos.solicitudes_vacaciones (id_funcionario,
																																	tipo_vinculacion,
																																	dependencia_id,
																																	fecha_desde,
																																	fecha_hasta,
																																	total_dias_habiles,
																																	observacion,
																																	estado,
																																	fecha_creacion,
																																	usuario_creador) 
	VALUES (':1',':2',':3',':4',':5',':6',':7',':8',':9',':10')
		RETURNING id",
		$id_funcionario,
		$tipo_vinculacion,
		$dependencia_id,
		$fecha_desde,
		$fecha_hasta,
		$total_dias_habiles,
		$observacion,
		$estado,
		$fecha_creacion,
		$usuario_creador);
	//debug_to_console($sqlInsertSolicitudesVacaciones);

// Ejecutar la consulta
$resultSolicitudesVacaciones = DB::Query($sqlInsertSolicitudesVacaciones);

// Obtener el ID generado de la solicitud
$row_solicitudes_vacaciones = $resultSolicitudesVacaciones->fetchAssoc();
$solicitud_vacacion_id = $row_solicitudes_vacaciones['id'];
	
/*==============================================================
=            CONTROL DE FLUJO PHPRUNNER                        =
==============================================================*/
/**
 * return false:
 *  - Evita que PHPRunner haga el INSERT automático
 *  - Se usa porque el INSERT ya se realizó manualmente
 */
return false;


;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		/*****************************************************************
 * EVENTO: Custom Record Update (EDIT)
 * MÓDULO: Solicitudes de Vacaciones
 * DESCRIPCIÓN:
 *  - Actualiza los datos editables de una solicitud de vacaciones
 *  - Registra la fecha de actualización
 *  - Mantiene intactos los campos de auditoría y control
 *****************************************************************/


/*==============================================================
=            ACTUALIZACIÓN DE SOLICITUD DE VACACIONES          =
==============================================================*/
/**
 * Se actualizan únicamente los campos permitidos en la edición:
 *  - tipo_vinculacion
 *  - dependencia_id
 *  - fechas del período solicitado
 *  - total de días hábiles
 *  - observación
 *
 * La fecha de actualización se asigna automáticamente.
 */

// Actualizar solicitud vacacion funcionario
$update_solicitud_vacaciones = DB::PrepareSQL(
	"UPDATE rrhh_permisos.solicitudes_vacaciones 
		SET tipo_vinculacion = ':1',
				dependencia_id = ':2',
				fecha_desde = ':3',
				fecha_hasta = ':4',
				total_dias_habiles = ':5',
				observacion = ':6',
				fecha_actualizacion = ':7'
	WHERE id = ':8'",
	$values["tipo_vinculacion"],
	$values["dependencia_id"],
	$values["fecha_desde"],
	$values["fecha_hasta"],
	$values["total_dias_habiles"],
	$values["observacion"],
	now(),
	$values["id"]
);

// Ejecutar la actualización
DB::Exec($update_solicitud_vacaciones);

/*==============================================================
=            CONTROL DE FLUJO PHPRUNNER                        =
==============================================================*/
/**
 * return false:
 *  - Evita que PHPRunner ejecute su UPDATE automático
 *  - Se usa porque la actualización ya fue manejada manualmente
 */
return false;


;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
